### ISSUE TITLE
Error converting summary statistic

### ISSUE THREAD

**Issue by geneticstudent** [bulik/ldsc#125]
Hi, first, I'm sorry to write questions at friday night.

While running munge_sumstats.py, I found a error about median value of beta.

Error is the following sentences.

Call:
./munge_sumstats.py \
--out YY.assoc1 \
--merge-alleles YY.assoc1.snp.snplist \
--N 27130.0 \
--sumstats YY.assoc1.ld.txt

Interpreting column names as follows:
a1:     Allele 1, interpreted as ref allele for signed sumstat.
pval:   p-Value
beta:   [linear/logistic] regression coefficient (0 --> no effect; above 0 --> A1 is trait/risk increasing)
snpid:  Variant ID (e.g., rs number)
a2:     Allele 2, interpreted as non-ref allele for signed sumstat.

Reading list of SNPs for allele merge from YY.assoc1.snp.snplist
Read 27130 SNPs for allele merge.
Reading sumstats from YY.assoc1.ld.txt into memory 5000000 SNPs at a time.
. done
Read 27130 SNPs from --sumstats file.
Removed 0 SNPs not in --merge-alleles.
Removed 0 SNPs with missing values.
Removed 0 SNPs with INFO <= 0.9.
Removed 0 SNPs with MAF <= 0.01.
Removed 0 SNPs with out-of-bounds p-values.
Removed 268 variants that were not SNPs or were strand-ambiguous.
26862 SNPs remain.
Removed 0 SNPs with duplicated rs numbers (26862 SNPs remain).
Using N = 27130.0

ERROR converting summary statistics:

Traceback (most recent call last):
  File "C:/Users/inha/ldsc/munge_sumstats.py", line 701, in munge_sumstats
    check_median(dat.SIGNED_SUMSTAT, signed_sumstat_null, 0.1, sign_cname))
  File "C:/Users/inha/ldsc/munge_sumstats.py", line 373, in check_median
    raise ValueError(msg.format(F=name, M=expected_median, V=round(m, 2)))
ValueError: WARNING: median value of beta is 0.41 (should be close to 0). This column may be mislabeled.

Conversion finished at Fri Jun 29 21:30:57 2018
Total time elapsed: 0.27s
Traceback (most recent call last):
  File "C:/Users/inha/ldsc/munge_sumstats.py", line 746, in <module>
    munge_sumstats(parser.parse_args(), p=True)
  File "C:/Users/inha/ldsc/munge_sumstats.py", line 701, in munge_sumstats
    check_median(dat.SIGNED_SUMSTAT, signed_sumstat_null, 0.1, sign_cname))
  File "C:/Users/inha/ldsc/munge_sumstats.py", line 373, in check_median
    raise ValueError(msg.format(F=name, M=expected_median, V=round(m, 2)))
ValueError: WARNING: median value of beta is 0.41 (should be close to 0). This column may be mislabeled.

Here, I don't know why ldsc calculate a median value of beta and why ldsc produce an error.

I hope that someone explain why ldsc calculate a median value of beta and provide me solutions for this error.

**Comment by uglymind** [comment]
I come with this problem too...desperate

**Comment by Saswata-Naha** [comment]
LDSC calculate the median of summary statistics to verify if the summary statistics is correctly levelled or not.

**Comment by shuai19910911** [comment]
You can get the Z value by beta and se, then add this '--ignore beta' when you are running.
