### ISSUE TITLE
Error converting summary statistics

### ISSUE THREAD

**Issue by cmfa26** [bulik/ldsc#131]
Hi,
While running munge_sumstats.py, I found a error about: SNP column was not find.
I following the tutorial, I did the download of all data (my_data_input and w_hm3.snplist) and software/packages, however I found this error:

Traceback (most recent call last):
  File "./munge_sumstats.py", line 746, in <module>
    munge_sumstats(parser.parse_args(), p=True)
  File "./munge_sumstats.py", line 627, in munge_sumstats
    raise ValueError('Could not find {C} column.'.format(C=c))
ValueError: Could not find SNP column.

Could help me to figure out how to handle this kind of error?

**Comment by rkwalters** [comment]
Hi,

As the error states, this indicates munge_sumstats.py isn't able to find a SNP column in your input summary statistics. There's a few different common issues that could yield this error:

- The header for a required column isn't one of the recognized values. E.g. for the SNP column, which is expected to include rsids, munge_sumstats.py will recognize "snp", "markername", "snpid", "rs", "rsid", "rs_number", or "rs_numbers" (all case insensitive). If it's not one of those, you can specify what your file is using as a header for that field using the "--snp" argument.

- The file format of the summary stats isn't supported. Munge_sumstats assumes the input summary stats are whitespace delimited (after decompression) with a header row. Comma-delimited files, or other separators, or tab-delimited files that allow spaces within a field and/or indicate missing values by multiple tabs will not parse correctly.

- The summary stats are compressed using a format that isn't supported by munge_sumstats. The currently supported options are plain text, gzip (*.gz), or bzip2 (*.bz2), identified by the filename. If your input summary stats are compressed with a different format (e.g. .zip, as is the case for the example scz/bip files used in the tutorial on the github wiki) you'll need to decompress the file before running munge.

If none of these solve it, it would be helpful to see the full command line you're using to run munge_sumstats.py and an example of the first few rows of your input summary statistics. (Can email those separately if you're more comfortable sharing those individually rather than posting to this issues board.)

Cheers,
Raymond

**Comment by cmfa26** [comment]
Hi,

thank you so much for your attention.

I could solve this problem with SNP, but now a new problem has arisen. Could you help me again?

Now the following error appears:
Conversion finished at Thu Sep  6 21:04:57 2018
Total time elapsed: 1.49s
Traceback (most recent call last):
  File "./munge_sumstats.py", line 746, in <module>
    munge_sumstats(parser.parse_args(), p=True)
  File "./munge_sumstats.py", line 686, in munge_sumstats
    dat = parse_dat(dat_gen, cname_translation, merge_alleles, log, args)
  File "./munge_sumstats.py", line 238, in parse_dat
    for block_num, dat in enumerate(dat_gen):
  File "/home/cmc329/anaconda2/lib/python2.7/site-packages/pandas/io/parsers.py", line 716, in __iter__
    yield self.read(self.chunksize)
  File "/home/cmc329/anaconda2/lib/python2.7/site-packages/pandas/io/parsers.py", line 740, in read
    ret = self._engine.read(nrows)
  File "/home/cmc329/anaconda2/lib/python2.7/site-packages/pandas/io/parsers.py", line 1187, in read
    data = self._reader.read(nrows)
  File "pandas/parser.pyx", line 766, in pandas.parser.TextReader.read (pandas/parser.c:8082)
  File "pandas/parser.pyx", line 800, in pandas.parser.TextReader._read_low_memory (pandas/parser.c:8538)
  File "pandas/parser.pyx", line 868, in pandas.parser.TextReader._read_rows (pandas/parser.c:9465)
  File "pandas/parser.pyx", line 975, in pandas.parser.TextReader._convert_column_data (pandas/parser.c:10858)
  File "pandas/parser.pyx", line 1054, in pandas.parser.TextReader._convert_tokens (pandas/parser.c:12095)
ValueError: could not convert string to float: rs187212831

I tryed convert the rsid column to numeric data, but without success.

Thank you again.

Best regards.

Carolina

________________________________
De: rkwalters <notifications@github.com>
Enviado: quinta-feira, 6 de setembro de 2018 16:01
Para: bulik/ldsc
Cc: cmfa26; Author
Assunto: Re: [bulik/ldsc] Error converting summary statistics (#131)

Hi,

As the error states, this indicates munge_sumstats.py isn't able to find a SNP column in your input summary statistics. There's a few different common issues that could yield this error:

- The header for a required column isn't one of the recognized values. E.g. for the SNP column, which is expected to include rsids, munge_sumstats.py will recognize "snp", "markername", "snpid", "rs", "rsid", "rs_number", or "rs_numbers" (all case insensitive). If it's not one of those, you can specify what your file is using as a header for that field using the "--snp" argument.

- The file format of the summary stats isn't supported. Munge_sumstats assumes the input summary stats are whitespace delimited (after decompression) with a header row. Comma-delimited files, or other separators, or tab-delimited files that allow spaces within a field and/or indicate missing values by multiple tabs will not parse correctly.

- The summary stats are compressed using a format that isn't supported by munge_sumstats. The currently supported options are plain text, gzip (*.gz), or bzip2 (*.bz2), identified by the filename. If your input summary stats are compressed with a different format (e.g. .zip, as is the case for the example scz/bip files used in the tutorial on the github wiki) you'll need to decompress the file before running munge.

If none of these solve it, it would be helpful to see the full command line you're using to run munge_sumstats.py and an example of the first few rows of your input summary statistics. (Can email those separately if you're more comfortable sharing those individually rather than posting to this issues board.)

Cheers,
Raymond

**Comment by rkwalters** [comment]
Hi Carolina,

It shouldn't be trying to convert the SNP column to float. Based on the error, munge appears to be encountering "rs187212831" in the column of the input file that it thinks should contain the signed summary statistic (e.g. Z-score or beta or odds ratio). Is there possibly a mismatch between the header of your file and the data?

Cheers,
Raymond

**Comment by cmfa26** [comment]
Hi Raymond,

Thank you for your answer. I could solved this, I converted the column to float.

Sorry, but I have other question/error. Now appears the following message: 

Traceback (most recent call last):
  File "./munge_sumstats.py", line 686, in munge_sumstats
    dat = parse_dat(dat_gen, cname_translation, merge_alleles, log, args)
  File "./munge_sumstats.py", line 238, in parse_dat
    for block_num, dat in enumerate(dat_gen):
  File "/.conda/envs/ldsc/lib/python2.7/site-packages/pandas/io/parsers.py", line 723, in __iter__
    yield self.read(self.chunksize)
  File "/.conda/envs/ldsc/lib/python2.7/site-packages/pandas/io/parsers.py", line 755, in read
    df = DataFrame(col_dict, columns=columns, index=index)
  File "/.conda/envs/ldsc/lib/python2.7/site-packages/pandas/core/frame.py", line 226, in __init__
    mgr = self._init_dict(data, index, columns, dtype=dtype)
  File "/.conda/envs/ldsc/lib/python2.7/site-packages/pandas/core/frame.py", line 363, in _init_dict
    dtype=dtype)
  File "/.conda/envs/ldsc/lib/python2.7/site-packages/pandas/core/frame.py", line 5168, in _arrays_to_mgr
    return create_block_manager_from_arrays(arrays, arr_names, axes)
  File "/.conda/envs/ldsc/lib/python2.7/site-packages/pandas/core/internals.py", line 3911, in create_block_manager_from_arrays
    blocks = form_blocks(arrays, names, axes)
  File "/.conda/envs/ldsc/lib/python2.7/site-packages/pandas/core/internals.py", line 3980, in form_blocks
    float_blocks = _multi_blockify(float_items)
  File "/.conda/envs/ldsc/lib/python2.7/site-packages/pandas/core/internals.py", line 4063, in _multi_blockify
    list(tup_block), dtype)
  File "/.conda/envs/ldsc/lib/python2.7/site-packages/pandas/core/internals.py", line 4107, in _stack_arrays
    stacked = np.empty(shape, dtype=dtype)
MemoryError

This error suggests that I don't have memory to run this analysis?

Thank you again.
