### ISSUE TITLE
Error running munge_sumstats.py

### ISSUE THREAD

**Issue by frw5010** [bulik/ldsc#132]
The script starts, reads the input .txt file, and starts filtering appropriately. However, after removal of the few SNPs whose alleles do not match the --merge_alleles file, I receive the following error when using the munge_sumstats.py script: 

ERROR converting summary statistics:

Traceback (most recent call last):
  File "munge_sumstats.py", line 707, in munge_sumstats
    dat = allele_merge(dat, merge_alleles, log)
  File "munge_sumstats.py", line 445, in allele_merge
    dat.loc[~jj, [i for i in dat.columns if i != 'SNP']] = float('nan')
  File "/home/fas/polimanti/frw5/anaconda2/lib/python2.7/site-packages/pandas/core/indexing.py", line 188, in __seti                                    tem__
    indexer = self._get_setitem_indexer(key)
  File "/home/fas/polimanti/frw5/anaconda2/lib/python2.7/site-packages/pandas/core/indexing.py", line 166, in _get_s                                    etitem_indexer
    return self._convert_tuple(key, is_setter=True)
  File "/home/fas/polimanti/frw5/anaconda2/lib/python2.7/site-packages/pandas/core/indexing.py", line 247, in _conve                                    rt_tuple
    idx = self._convert_to_indexer(k, axis=i, is_setter=is_setter)
  File "/home/fas/polimanti/frw5/anaconda2/lib/python2.7/site-packages/pandas/core/indexing.py", line 1327, in _conv                                    ert_to_indexer
    .format(mask=objarr[mask]))
KeyError: '[-1 -1 -2 ... -1 -1 -1] not in index'

Thank you!

**Comment by frw5010** [comment]
Nevermind. This has been discussed in previous posts (104, 93).
