### ISSUE TITLE
Tutorial Cell type specific analyses fails

### ISSUE THREAD

**Issue by nadavrap** [bulik/ldsc#148]
I tried to follow the Wiki example for [cell type specific analysis](https://github.com/bulik/ldsc/wiki/Cell-type-specific-analyses). But I get an error while running munge_sumstats.py.
See the next output:

```*********************************************************************
* LD Score Regression (LDSC)
* Version 1.0.0
* (C) 2014-2015 Brendan Bulik-Sullivan and Hilary Finucane
* Broad Institute of MIT and Harvard / MIT Department of Mathematics
* GNU General Public License v3
*********************************************************************
Call:
./munge_sumstats.py \
--out UKBB_BMI \
--merge-alleles w_hm3.snplist \
--sumstats body_BMIz.sumstats.gz

Interpreting column names as follows:
INFO:   INFO score (imputation quality; higher --> better imputation)
EAF:    Allele frequency
A1:     Allele 1, interpreted as ref allele for signed sumstat.
P:      p-Value
Beta:   [linear/logistic] regression coefficient (0 --> no effect; above 0 --> A1 is trait/risk increasing)
A2:     Allele 2, interpreted as non-ref allele for signed sumstat.
SNP:    Variant ID (e.g., rs number)
N:      Sample size

Reading list of SNPs for allele merge from w_hm3.snplist
Read 1217311 SNPs for allele merge.
Reading sumstats from body_BMIz.sumstats.gz into memory 5000000 SNPs at a time.
WARNING: 1 SNPs had P outside of (0,1]. The P column may be mislabeled.
Read 12007571 SNPs from --sumstats file.
Removed 10796799 SNPs not in --merge-alleles.
Removed 0 SNPs with missing values.
Removed 14054 SNPs with INFO <= 0.9.
Removed 21965 SNPs with MAF <= 0.01.
Removed 1 SNPs with out-of-bounds p-values.
Removed 201 variants that were not SNPs or were strand-ambiguous.
1174551 SNPs remain.
Removed 270 SNPs with duplicated rs numbers (1174281 SNPs remain).
Removed 0 SNPs with N < 305216.0 (1174281 SNPs remain).
Median value of Beta was -8.56189e-06, which seems sensible.
Removed 136 SNPs whose alleles did not match --merge-alleles (1174145 SNPs remain).

ERROR converting summary statistics:

Traceback (most recent call last):
  File "../scripts/ldsc/munge_sumstats.py", line 707, in munge_sumstats
    dat = allele_merge(dat, merge_alleles, log)
  File "../scripts/ldsc/munge_sumstats.py", line 445, in allele_merge
    dat.loc[~jj, [i for i in dat.columns if i != 'SNP']] = float('nan')
  File "/Users/nadavrap/.local/lib/python2.7/site-packages/pandas/core/indexing.py", line 188, in __setitem__
    indexer = self._get_setitem_indexer(key)
  File "/Users/nadavrap/.local/lib/python2.7/site-packages/pandas/core/indexing.py", line 166, in _get_setitem_indexer
    return self._convert_tuple(key, is_setter=True)
  File "/Users/nadavrap/.local/lib/python2.7/site-packages/pandas/core/indexing.py", line 247, in _convert_tuple
    idx = self._convert_to_indexer(k, axis=i, is_setter=is_setter)
  File "/Users/nadavrap/.local/lib/python2.7/site-packages/pandas/core/indexing.py", line 1327, in _convert_to_indexer
    .format(mask=objarr[mask]))
KeyError: '[-2 -2 -2 ..., -1 -2 -2] not in index'


Conversion finished at Thu Mar  7 05:50:24 2019
Total time elapsed: 1.0m:18.35s
```

What can it be

**Comment by complexgenome** [comment]
Were you able to solve this?
