### ISSUE TITLE
Estimate heritability

### ISSUE THREAD

**Issue by smuchakiel** [bulik/ldsc#149]
Dear all,

I installed everything. I created the summary stats with:

python munge_sumstats.py --sumstats AD_META_GENOTYPED_ALL_ALLDIRECTIONS_RAREMETAL.txt2 --N 16208 --out AD --a1 ALT --a2 REF

I received the summary stats file for the correct input.

Then I am using this: 

python ldsc.py --h2 AD.sumstats.gz --out TEST_h2 --ref-ld-chr /home/osiron/storage2/heratibility/eur_w_ld_chr/ --w-ld-chr /home/osiron/storage2/heratibility/eur_w_ld_chr/

And i received this error message:

*********************************************************************
* LD Score Regression (LDSC)
* Version 1.0.0
* (C) 2014-2015 Brendan Bulik-Sullivan and Hilary Finucane
* Broad Institute of MIT and Harvard / MIT Department of Mathematics
* GNU General Public License v3
*********************************************************************
Call: 
./ldsc.py \
--h2 AD.sumstats.gz \
--ref-ld-chr eur_w_ld/ \
--out AD_h2 \
--w-ld-chr eur_w_ld_chr/ 

Beginning analysis at Mon Mar 11 17:47:03 2019
Reading summary statistics from AD.sumstats.gz ...
Read summary statistics for 128393 SNPs.
Reading reference panel LD Score from eur_w_ld/[1-22] ...
Traceback (most recent call last):
  File "ldsc.py", line 644, in <module>
    sumstats.estimate_h2(args, log)
  File "/home/user/ldsc-master/ldscore/sumstats.py", line 326, in estimate_h2
    args, log, args.h2)
  File "/home/user/ldsc-master/ldscore/sumstats.py", line 243, in _read_ld_sumstats
    ref_ld = _read_ref_ld(args, log)
  File "/home/user/ldsc-master/ldscore/sumstats.py", line 82, in _read_ref_ld
    'reference panel LD Score', ps.ldscore_fromlist)
  File "/home/user/ldsc-master/ldscore/sumstats.py", line 152, in _read_chr_split_files
    out = parsefunc(_splitp(chr_arg), _N_CHR, **kwargs)
  File "/home/user/ldsc-master/ldscore/parse.py", line 93, in ldscore_fromlist
    y = ldscore(fh, num)
  File "/home/user/ldsc-master/ldscore/parse.py", line 137, in ldscore
    s, compression = which_compression(first_fh)
  File "/home/user/ldsc-master/ldscore/parse.py", line 43, in which_compression
    raise IOError('Could not open {F}[./gz/bz2]'.format(F=fh))
IOError: Could not open eur_w_ld/1.l2.ldscore[./gz/bz2]

Analysis finished at Mon Mar 11 17:47:03 2019
Total time elapsed: 0.22s

Can somebody help me? I checked the other issues, didn't find any solution

**Comment by smuchakiel** [comment]
Hello there,

I fixed the problem. It was depending on the precalculated LD_scores. I did the calculation myself and now it is working.

Best,

**Comment by smuchakiel** [comment]
@Julia-Ramirez plz calculate the LD score again. It was working in my case.

**Comment by Julia-Ramirez** [comment]
I haven't calculated it. I have downloaded as specified in the website (https://github.com/bulik/ldsc/wiki/LD-Score-Estimation-Tutorial)

**Comment by Lassana1** [comment]
Hi smuchakiel, can you please provide the code used for calculating the LD scores? I get errors when following the wiki tutorial

**Comment by roxyisat-rex** [comment]
Hey Smuchakiel 

I got a very similar error (almost exactly the same). May I ask, when you say you calculated your LD scores again, what did you change? Did you just do it all over again with the same code/ input/ etc? Which bit did you do differently to make it work? Did the old LD score that didn't work out look a lot different than the new LD score that did work, like in terms of file structure and content? Any advice is helpful and welcomed! Thank you so much. 

Best, 
Roxy

**Comment by roxyisat-rex** [comment]
> Hello there,
> 
> I fixed the problem. It was depending on the precalculated LD_scores. I did the calculation myself and now it is working.
> 
> Best,
Hey Smuchakiel

I got a very similar error (almost exactly the same). May I ask, when you say you calculated your LD scores again, what did you change? Did you just do it all over again with the same code/ input/ etc? Which bit did you do differently to make it work? Did the old LD score that didn't work out look a lot different than the new LD score that did work, like in terms of file structure and content? Any advice is helpful and welcomed! Thank you so much.

Best,
Roxy

Sorry for posting again, I realised I didn't reply to you earlier.
