### ISSUE TITLE
munge_sumstats.py throwing error on simulated dataset

### ISSUE THREAD

**Issue by 35ajstern** [bulik/ldsc#150]
I am calling munge_sumstats.py in the following way:

```
./munge_sumstats.py \
--out test \
--N 2000.0 \
--sumstats example.sumstats.txt
```

and it's giving me this error:

`Reading list of SNPs for allele merge from test.assoc.linear.ldsc.snplist
Read 5484 SNPs for allele merge.
Reading sumstats from test.assoc.linear.ldsc into memory 5000000 SNPs at a time.
. done

ERROR converting summary statistics:

Traceback (most recent call last):
  File "ldsc/munge_sumstats.py", line 687, in munge_sumstats
    dat = parse_dat(dat_gen, cname_translation, merge_alleles, log, args)
  File "ldsc/munge_sumstats.py", line 302, in parse_dat
    dat = pd.concat(dat_list, axis=0).reset_index(drop=True)
  File "/Users/ajstern/anaconda3/envs/ldsc/lib/python2.7/site-packages/pandas/core/reshape/concat.py", line 206, in concat
    copy=copy)
  File "/Users/ajstern/anaconda3/envs/ldsc/lib/python2.7/site-packages/pandas/core/reshape/concat.py", line 239, in __init__
    raise ValueError('No objects to concatenate')
ValueError: No objects to concatenate

Conversion finished at Thu Mar 14 11:41:22 2019
Total time elapsed: 0.04s
Traceback (most recent call last):
  File "ldsc/munge_sumstats.py", line 747, in <module>
    munge_sumstats(parser.parse_args(), p=True)
  File "ldsc/munge_sumstats.py", line 687, in munge_sumstats
    dat = parse_dat(dat_gen, cname_translation, merge_alleles, log, args)
  File "ldsc/munge_sumstats.py", line 302, in parse_dat
    dat = pd.concat(dat_list, axis=0).reset_index(drop=True)
  File "/Users/ajstern/anaconda3/envs/ldsc/lib/python2.7/site-packages/pandas/core/reshape/concat.py", line 206, in concat
    copy=copy)
  File "/Users/ajstern/anaconda3/envs/ldsc/lib/python2.7/site-packages/pandas/core/reshape/concat.py", line 239, in __init__
    raise ValueError('No objects to concatenate')
ValueError: No objects to concatenate`

I've looked at other issues with the same error and I do not find any issues in the formatting of my files; eg

`$ head example.sumstats.txt

snpid chr bp a1 a2 beta INFO P
rs1000001	1	4243880	T	A	1.695	0.999	0.09024
rs1000002	1	7220677	T	A	1.21	0.999	0.2263
rs1000003	1	2689176	T	A	-0.6394	0.999	0.5227
rs1000004	1	562214	A	T	-1.208	0.999	0.2271
rs1000005	1	555656	T	A	-1.14	0.999	0.2543
rs1000006	1	7128203	A	T	-1.495	0.999	0.135
rs1000007	1	7260787	A	T	-0.8599	0.999	0.39
rs1000008	1	546715	A	T	-1.14	0.999	0.2543
rs1000009	1	571533	T	A	-1.208	0.999	0.2271`

and I rigorously test this I do not get any missing fields in the rows.

Any idea what is causing the error? Does it have to do with using made-up RSIDs?

Thanks,
aaron

**Comment by alesssia** [comment]
Can this be linked to #166? With made-up RSIDs not included in the file specified `--merge_alleles` (which I suppose it is some default file since you are not specifying it but it is reported in the log)?

**Comment by Arslan-Zaidi** [comment]
I had the same issue with my simulated dataset. I ended up carrying out weighted regression independently, which yielded results that made sense. Though would still like to know if this gets resolved at some point.
