### ISSUE TITLE
munge_sumstats.py error

### ISSUE THREAD

**Issue by lormmy** [bulik/ldsc#159]
Hi-
Thanks for making this great software available. I'm running into an error when using munge_sumstats.py.

**Here's the error message**
E:\ldsc>munge_sumstats.py --sumstats pgc.cross.BIP11.2013-05.txt --N 11810 --out
 scz --merge-alleles w_hm3.snplist
<_io.BufferedWriter name='scz.log'> ********************************************
*************************
* LD Score Regression (LDSC)
* Version 1.0.0
* (C) 2014-2015 Brendan Bulik-Sullivan and Hilary Finucane
* Broad Institute of MIT and Harvard / MIT Department of Mathematics
* GNU General Public License v3
*********************************************************************
Call:
./munge_sumstats.py \
--sumstats pgc.cross.BIP11.2013-05.txt \
--N 11810.0 \
--out scz \
--merge-alleles w_hm3.snplist

*********************************************************************
* LD Score Regression (LDSC)
* Version 1.0.0
* (C) 2014-2015 Brendan Bulik-Sullivan and Hilary Finucane
* Broad Institute of MIT and Harvard / MIT Department of Mathematics
* GNU General Public License v3
*********************************************************************
Call:
./munge_sumstats.py \
--sumstats pgc.cross.BIP11.2013-05.txt \
--N 11810.0 \
--out scz \
--merge-alleles w_hm3.snplist

<_io.BufferedWriter name='scz.log'>
ERROR converting summary statistics:

ERROR converting summary statistics:

<_io.BufferedWriter name='scz.log'>
Conversion finished at Mon Jul 22 16:31:01 2019

Conversion finished at Mon Jul 22 16:31:01 2019
<_io.BufferedWriter name='scz.log'> Total time elapsed: 0.65s
Total time elapsed: 0.65s
Traceback (most recent call last):
  File "E:\ldsc\munge_sumstats.py", line 566, in munge_sumstats
    flag_cnames, mod_default_cnames, ignore_cnames)
  File "E:\ldsc\munge_sumstats.py", line 147, in get_cname_map
    {x: default[x] for x in default if x not in clean_ignore + flag.keys()})
  File "E:\ldsc\munge_sumstats.py", line 147, in <dictcomp>
    {x: default[x] for x in default if x not in clean_ignore + flag.keys()})
TypeError: can only concatenate list (not "dict_keys") to list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\ldsc\munge_sumstats.py", line 746, in <module>
    munge_sumstats(parser.parse_args(), p=True)
  File "E:\ldsc\munge_sumstats.py", line 738, in munge_sumstats
    log.log(traceback.format_exc(ex))
  File "C:\Python37\lib\traceback.py", line 167, in format_exc
    return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))
  File "C:\Python37\lib\traceback.py", line 121, in format_exception
    type(value), value, tb, limit=limit).format(chain=chain))
  File "C:\Python37\lib\traceback.py", line 508, in __init__
    capture_locals=capture_locals)
  File "C:\Python37\lib\traceback.py", line 337, in extract
    if limit >= 0:
TypeError: '>=' not supported between instances of 'TypeError' and 'int'

Thanks for your help!
Wenjie Liu

**Comment by lormmy** [comment]
I have fixed this issue. 
flag.keys() changes into list(flag.keys())
However, I met a new error:
/-------------------------------------------------------------------------------------------------------
<_io.BufferedWriter name='scz.log'> Total time elapsed: 14.93s
Total time elapsed: 14.93s
Traceback (most recent call last):
  File "E:\ldsc\munge_sumstats.py", line 709, in munge_sumstats
    dat = allele_merge(dat, merge_alleles, log)
  File "E:\ldsc\munge_sumstats.py", line 445, in allele_merge
    dat.loc[~jj, [i for i in dat.columns if i != 'SNP']] = float('nan')
  File "C:\Python37\lib\site-packages\pandas\core\indexing.py", line 189, in __s
etitem__
    indexer = self._get_setitem_indexer(key)
  File "C:\Python37\lib\site-packages\pandas\core\indexing.py", line 167, in _ge
t_setitem_indexer
    return self._convert_tuple(key, is_setter=True)
  File "C:\Python37\lib\site-packages\pandas\core\indexing.py", line 248, in _co
nvert_tuple
    idx = self._convert_to_indexer(k, axis=i, is_setter=is_setter)
  File "C:\Python37\lib\site-packages\pandas\core\indexing.py", line 1354, in _c
onvert_to_indexer
    return self._get_listlike_indexer(obj, axis, **kwargs)[1]
  File "C:\Python37\lib\site-packages\pandas\core\indexing.py", line 1161, in _g
et_listlike_indexer
    raise_missing=raise_missing)
  File "C:\Python37\lib\site-packages\pandas\core\indexing.py", line 1246, in _v
alidate_read_indexer
    key=key, axis=self.obj._get_axis_name(axis)))
KeyError: "None of [Int64Index([-1, -1, -2, -1, -1, -1, -2, -2, -1, -1,\n
     ...\n            -1, -1, -1, -1, -1, -1, -1, -1, -1, -1], dtype='int64', le
ngth=1217311)] are in the [index]"

How to solve this problem?
Thanks for your help.
Wenjie Liu

**Comment by rowenachz** [comment]
Hi, did you manage to find a way around this? I run into the same issue here. Thanks very much in advance!

**Comment by judycoder** [comment]
> Hi-
> Thanks for making this great software available. I'm running into an error when using munge_sumstats.py.
> 
> **Here's the error message**
> E:\ldsc>munge_sumstats.py --sumstats pgc.cross.BIP11.2013-05.txt --N 11810 --out
> scz --merge-alleles w_hm3.snplist
> <_io.BufferedWriter name='scz.log'> ********************************************
> 
> * LD Score Regression (LDSC)
> * Version 1.0.0
> * (C) 2014-2015 Brendan Bulik-Sullivan and Hilary Finucane
> * Broad Institute of MIT and Harvard / MIT Department of Mathematics
> * GNU General Public License v3
> 
> Call:
> ./munge_sumstats.py
> --sumstats pgc.cross.BIP11.2013-05.txt
> --N 11810.0
> --out scz
> --merge-alleles w_hm3.snplist
> 
> * LD Score Regression (LDSC)
> * Version 1.0.0
> * (C) 2014-2015 Brendan Bulik-Sullivan and Hilary Finucane
> * Broad Institute of MIT and Harvard / MIT Department of Mathematics
> * GNU General Public License v3
> 
> Call:
> ./munge_sumstats.py
> --sumstats pgc.cross.BIP11.2013-05.txt
> --N 11810.0
> --out scz
> --merge-alleles w_hm3.snplist
> 
> <_io.BufferedWriter name='scz.log'>
> ERROR converting summary statistics:
> 
> ERROR converting summary statistics:
> 
> <_io.BufferedWriter name='scz.log'>
> Conversion finished at Mon Jul 22 16:31:01 2019
> 
> Conversion finished at Mon Jul 22 16:31:01 2019
> <_io.BufferedWriter name='scz.log'> Total time elapsed: 0.65s
> Total time elapsed: 0.65s
> Traceback (most recent call last):
> File "E:\ldsc\munge_sumstats.py", line 566, in munge_sumstats
> flag_cnames, mod_default_cnames, ignore_cnames)
> File "E:\ldsc\munge_sumstats.py", line 147, in get_cname_map
> {x: default[x] for x in default if x not in clean_ignore + flag.keys()})
> File "E:\ldsc\munge_sumstats.py", line 147, in
> {x: default[x] for x in default if x not in clean_ignore + flag.keys()})
> TypeError: can only concatenate list (not "dict_keys") to list
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "E:\ldsc\munge_sumstats.py", line 746, in
> munge_sumstats(parser.parse_args(), p=True)
> File "E:\ldsc\munge_sumstats.py", line 738, in munge_sumstats
> log.log(traceback.format_exc(ex))
> File "C:\Python37\lib\traceback.py", line 167, in format_exc
> return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))
> File "C:\Python37\lib\traceback.py", line 121, in format_exception
> type(value), value, tb, limit=limit).format(chain=chain))
> File "C:\Python37\lib\traceback.py", line 508, in **init**
> capture_locals=capture_locals)
> File "C:\Python37\lib\traceback.py", line 337, in extract
> if limit >= 0:
> TypeError: '>=' not supported between instances of 'TypeError' and 'int'
> 
> Thanks for your help!
> Wenjie Liu

I have encountered the same problem as you did. 
I am wondering how did you solve this problem? Could you please provide your way of solving it? 

Thanks, 
Judy Chen

**Comment by lormmy** [comment]
The python should > 2.7.9 and < 3.0 in linux system. I solved the problem from this way.
Wenjie Liu

**Comment by lormmy** [comment]
> > Hi-
> > Thanks for making this great software available. I'm running into an error when using munge_sumstats.py.
> > **Here's the error message**
> > E:\ldsc>munge_sumstats.py --sumstats pgc.cross.BIP11.2013-05.txt --N 11810 --out
> > scz --merge-alleles w_hm3.snplist
> > <_io.BufferedWriter name='scz.log'> ********************************************
> > 
> > * LD Score Regression (LDSC)
> > * Version 1.0.0
> > * (C) 2014-2015 Brendan Bulik-Sullivan and Hilary Finucane
> > * Broad Institute of MIT and Harvard / MIT Department of Mathematics
> > * GNU General Public License v3
> > 
> > Call:
> > ./munge_sumstats.py
> > --sumstats pgc.cross.BIP11.2013-05.txt
> > --N 11810.0
> > --out scz
> > --merge-alleles w_hm3.snplist
> > 
> > * LD Score Regression (LDSC)
> > * Version 1.0.0
> > * (C) 2014-2015 Brendan Bulik-Sullivan and Hilary Finucane
> > * Broad Institute of MIT and Harvard / MIT Department of Mathematics
> > * GNU General Public License v3
> > 
> > Call:
> > ./munge_sumstats.py
> > --sumstats pgc.cross.BIP11.2013-05.txt
> > --N 11810.0
> > --out scz
> > --merge-alleles w_hm3.snplist
> > <_io.BufferedWriter name='scz.log'>
> > ERROR converting summary statistics:
> > ERROR converting summary statistics:
> > <_io.BufferedWriter name='scz.log'>
> > Conversion finished at Mon Jul 22 16:31:01 2019
> > Conversion finished at Mon Jul 22 16:31:01 2019
> > <_io.BufferedWriter name='scz.log'> Total time elapsed: 0.65s
> > Total time elapsed: 0.65s
> > Traceback (most recent call last):
> > File "E:\ldsc\munge_sumstats.py", line 566, in munge_sumstats
> > flag_cnames, mod_default_cnames, ignore_cnames)
> > File "E:\ldsc\munge_sumstats.py", line 147, in get_cname_map
> > {x: default[x] for x in default if x not in clean_ignore + flag.keys()})
> > File "E:\ldsc\munge_sumstats.py", line 147, in
> > {x: default[x] for x in default if x not in clean_ignore + flag.keys()})
> > TypeError: can only concatenate list (not "dict_keys") to list
> > During handling of the above exception, another exception occurred:
> > Traceback (most recent call last):
> > File "E:\ldsc\munge_sumstats.py", line 746, in
> > munge_sumstats(parser.parse_args(), p=True)
> > File "E:\ldsc\munge_sumstats.py", line 738, in munge_sumstats
> > log.log(traceback.format_exc(ex))
> > File "C:\Python37\lib\traceback.py", line 167, in format_exc
> > return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))
> > File "C:\Python37\lib\traceback.py", line 121, in format_exception
> > type(value), value, tb, limit=limit).format(chain=chain))
> > File "C:\Python37\lib\traceback.py", line 508, in **init**
> > capture_locals=capture_locals)
> > File "C:\Python37\lib\traceback.py", line 337, in extract
> > if limit >= 0:
> > TypeError: '>=' not supported between instances of 'TypeError' and 'int'
> > Thanks for your help!
> > Wenjie Liu
> 
> I have encountered the same problem as you did.
> I am wondering how did you solve this problem? Could you please provide your way of solving it?
> 
> Thanks,
> Judy Chen

The python should > 2.7.9 and < 3.0 in linux system. I solved the problem from this way.
Wenjie Liu
