### ISSUE TITLE
Cell type specific analysis crashes with specific traits using a modified baseline model

### ISSUE THREAD

**Issue by laurajb** [bulik/ldsc#165]
Hello,

I am running a cell type specific analysis with a modified baseline model where I added an extra category, it works when I use the summary statistics for one trait but crashes for other traits giving me the following error:

Call: 
./ldsc.py \
--h2-cts trait.sumstats \
--ref-ld-chr modified_V1.1_baseline. \
--out CTS_trait_modified_V1.1_baseline \
--ref-ld-chr-cts category.ldcts \
--w-ld-chr 1000G_Phase3_weights_hm3_no_MHC/weights.hm3_noMHC. 

Reading summary statistics from trait.sumstats ...
Read summary statistics for 750635 SNPs.
Reading reference panel LD Score from modified_V1.1_baseline.[1-22] ...
Read reference panel LD Scores for 1190321 SNPs.
Removing partitioned LD Scores with zero variance.
Reading regression weight LD Score from 1000G_Phase3_weights_hm3_no_MHC/weights.hm3_noMHC.[1-22] ...
Read regression weight LD Scores for 1187349 SNPs.
After merging with reference panel LD, 750635 SNPs remain.
After merging with regression SNP LD, 750635 SNPs remain.
Removed 0 SNPs with chi^2 > 80 (750635 SNPs remain)
Reading cts reference panel LD Score from category.[1-22] ...
Performing regression.
Traceback (most recent call last):
  File "/mnt/Software/LD/ldsc/ldsc.py", line 646, in <module>
    sumstats.cell_type_specific(args, log)
  File "/mnt/Software/LD/ldsc/ldscore/sumstats.py", line 300, in cell_type_specific
    twostep=None, old_weights=True)
  File "/mnt/Software/LD/ldsc/ldscore/regressions.py", line 346, in __init__
    slow=slow, step1_ii=step1_ii, old_weights=old_weights)
  File "/mnt/Software/LD/ldsc/ldscore/regressions.py", line 219, in __init__
    self.tot, self.tot_cov, self.tot_se = self._tot(self.cat, self.cat_cov)
  File "/mnt/Software/LD/ldsc/ldscore/regressions.py", line 282, in _tot
    tot_se = np.sqrt(tot_cov)
FloatingPointError: invalid value encountered in sqrt

If I run it with a different baseline model it works so it seems like there's an issue with the model and specific traits.

I hope you can help me find out what is happening.

All the best,

Laura

**Comment by qi825** [comment]
Have you solved the problem ?
