### ISSUE TITLE
pandas error

### ISSUE THREAD

**Issue by babak-ra** [bulik/ldsc#173]
I get the following error when I run `./ldsc.py --help`:

```
(ldsc) root@image:/opt/ldsc# ./ldsc.py --help
Traceback (most recent call last):
  File "./ldsc.py", line 13, in <module>
    import ldscore.parse as ps
  File "/opt/ldsc/ldscore/parse.py", line 10, in <module>
    import pandas as pd
  File "/opt/Anaconda2-2019.10/envs/ldsc/lib/python2.7/site-packages/pandas/__init__.py", line 26, in <module>
    from pandas._libs import (hashtable as _hashtable,
  File "/opt/Anaconda2-2019.10/envs/ldsc/lib/python2.7/site-packages/pandas/_libs/__init__.py", line 3, in <module>
    from .tslib import iNaT, NaT, Timestamp, Timedelta, OutOfBoundsDatetime
  File "pandas/_libs/src/numpy.pxd", line 865, in init pandas._libs.tslib (pandas/_libs/tslib.c:117321)
ValueError: numpy.ufunc has the wrong size, try recompiling. Expected 192, got 216
```
conda version is 4.7.12.

Any ideas?

**Comment by casalex** [comment]
I had this too -- a quick upgrade to numpy solved it for me:

pip install --upgrade numpy==1.16.0

**Comment by babak-ra** [comment]
Thanks. That worked for me too, but if that is the case, the [environment](https://github.com/bulik/ldsc/blob/master/environment.yml) file needs to be updated.
