### ISSUE TITLE
FloatingPointError: invalid value encountered in less_equal

### ISSUE THREAD

**Issue by dekim22114** [bulik/ldsc#174]
*********************************************************************
* LD Score Regression (LDSC)
* Version 1.0.1
* (C) 2014-2019 Brendan Bulik-Sullivan and Hilary Finucane
* Broad Institute of MIT and Harvard / MIT Department of Mathematics
* GNU General Public License v3
*********************************************************************
Call:
./ldsc.py \
--ref-ld-chr eur_w_ld_chr/ \
--out JIA_t1d \
--rg JIA_munge.sumstats.gz,PASS/PASS_Type_1_Diabetes.anno.sumstats \
--w-ld-chr eur_w_ld_chr/

Beginning analysis at Fri Nov  1 20:19:43 2019
Reading summary statistics from JIA_munge.sumstats.gz ...
Read summary statistics for 104285 SNPs.
Reading reference panel LD Score from eur_w_ld_chr/[1-22] ...
Read reference panel LD Scores for 1290028 SNPs.
Removing partitioned LD Scores with zero variance.
Reading regression weight LD Score from eur_w_ld_chr/[1-22] ...
Read regression weight LD Scores for 1290028 SNPs.
After merging with reference panel LD, 48398 SNPs remain.
After merging with regression SNP LD, 48398 SNPs remain.
Computing rg for phenotype 2/2
Reading summary statistics from PASS/PASS_Type_1_Diabetes.anno.sumstats ...
Read summary statistics for 915517 SNPs.
After merging with summary statistics, 39528 SNPs remain.
39528 SNPs with valid alleles.
WARNING: number of SNPs less than 200k; this is almost always bad.
/home/de/fusion/fusion_twas-master/ldsc/ldscore/sumstats.py:532: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  ref_ld = sumstats.as_matrix(columns=ref_ld_cnames)

**ERROR computing rg for phenotype 2/2, from file PASS/PASS_Type_1_Diabetes.anno.sumstats.
Traceback (most recent call last):
  File "/home/de/fusion/fusion_twas-master/ldsc/ldscore/sumstats.py", line 410, in estimate_rg
    rghat = _rg(loop, args, log, M_annot, ref_ld_cnames, w_ld_cname, i)
  File "/home/de/fusion/fusion_twas-master/ldsc/ldscore/sumstats.py", line 539, in _rg
    intercept_gencov=intercepts[2], n_blocks=n_blocks, twostep=args.two_step)
  File "/home/de/fusion/fusion_twas-master/ldsc/ldscore/regressions.py", line 690, in __init__
    slow=slow, twostep=twostep)
  File "/home/de/fusion/fusion_twas-master/ldsc/ldscore/regressions.py", line 346, in __init__
    slow=slow, step1_ii=step1_ii, old_weights=old_weights)
  File "/home/de/fusion/fusion_twas-master/ldsc/ldscore/regressions.py", line 213, in __init__
    x, yp, update_func, n_blocks, slow=slow, w=initial_w)
  File "/home/de/fusion/fusion_twas-master/ldsc/ldscore/irwls.py", line 66, in __init__
    x, y, update_func, n_blocks, w, slow=slow, separators=separators)
  File "/home/de/fusion/fusion_twas-master/ldsc/ldscore/irwls.py", line 113, in irwls
    new_w = np.sqrt(update_func(cls.wls(x, y, w)))
  File "/home/de/fusion/fusion_twas-master/ldsc/ldscore/irwls.py", line 159, in wls
    x = cls._weight(x, w)
  File "/home/de/fusion/fusion_twas-master/ldsc/ldscore/irwls.py", line 187, in _weight
    if np.any(w <= 0):
FloatingPointError: invalid value encountered in less_equal**

**Comment by bcrone** [comment]
Also receiving this error - bumping for visibility

**Comment by sandiassaf** [comment]
I am encountering the same issue. Was anyone able to resolve this?

**Comment by kllrdr** [comment]
Hi all,

I got the same error.
I could figure out that the problem is having NaN (Not a Number) in our data, which is a member of a numeric data type that can be interpreted as a value that is undefined or unrepresentable, especially in floating-point arithmetic. Has anyone solved this problem since posting?

**Comment by chenming9453** [comment]
Hi all, I got the same error here.  I am wondering if anyone has solved this problem?

**Comment by kllrdr** [comment]
Hi,

Yes, the problem is having missing values somewhere in your annotations
(which you used to compute LD scores). So, some SNPs are missing some
values for different partitions.
Example:

          AN1 AN2 AN3 AN4
SNP1 0.34 0.23 0.45 0.12
SNP2 0.24 0.45
SNP3 0.12 0.46 0.23 0.34
SNP4 0.34 0.22 0.43

If you open your ldscore.gz files, you will see NaN values instead of LD
scores for various annotations.
I made my annotations again and the problem was solved.

**Comment by goodluckncb** [comment]
I also ran into this problem, I built the sumstats.gz file myself and needed to determine if there were nan, inf,-inf equivalents in the "Z" column, just make those values clear

**Comment by isabellebond** [comment]
Hi,

I've been using the files from eur_w_ld_chr/ and have run all my sumstats through munge_sumstats to get them in the correct format and am also getting this error. I've checked for missing data in any of the .ldscore files and haven't found anything. Does anyone know of anything else that might be causing this issue? Thank you so much

**Comment by AndreaG5** [comment]
Hi all,

I am encountering the same problem. I checked for missing values in my *.sumstats.gz file, but it doesn't seem to be any of NA/Na/NaN. 
Does anyone solve the problem in any way?

Thanks
