### ISSUE TITLE
numpy==1.16.0 !!!

### ISSUE THREAD

**Issue by jiehuang001** [bulik/ldsc#180]
Hi, there:

It took me a week to finally install LDSC successfully into my Windows10 embedded Ubuntu. 
I tried Anaconda2 and Anaconda3 and both, and played with a few other things.

Finally, I found that I simply need to change numpy==1.12 to numpy==1.16.0 in the environment.yml file, and this worked for Anaconda3. I found this solution actually from the post #173 on this forum.

So, can you please confirm this is the case and then fix the environment.yml file from the downloading, so that others will not run into the same problem?

Thanks!

Jie

**Comment by NathanSkene** [comment]
I had the same issue installing on Ubuntu 19.04

Using the environment.yml that comes with the package, when I run "./ldsc.py -h" I get:

`Traceback (most recent call last):
  File "./ldsc.py", line 13, in <module>
    import ldscore.parse as ps
  File "/home/nskene/ldsc/ldscore/parse.py", line 10, in <module>
    import pandas as pd
  File "/home/nskene/anaconda3/envs/ldsc/lib/python2.7/site-packages/pandas/__init__.py", line 26, in <module>
    from pandas._libs import (hashtable as _hashtable,
  File "/home/nskene/anaconda3/envs/ldsc/lib/python2.7/site-packages/pandas/_libs/__init__.py", line 3, in <module>
    from .tslib import iNaT, NaT, Timestamp, Timedelta, OutOfBoundsDatetime
  File "pandas/_libs/src/numpy.pxd", line 865, in init pandas._libs.tslib (pandas/_libs/tslib.c:117321)
ValueError: numpy.ufunc has the wrong size, try recompiling. Expected 192, got 216`

Noticed that it was suggested in a different git repo (https://github.com/automl/auto-sklearn/issues/621#issuecomment-535761601) that this is due to the Numpy version. Ran `pip install --upgrade numpy==1.16.0` and it works fine.

**Comment by ja-ox** [comment]
I've proposed a fix to this by updating the numpy version in requirements.txt:

https://github.com/bulik/ldsc/issues/180
