### ISSUE TITLE
IOError could not open 

### ISSUE THREAD

**Issue by roxyisat-rex** [bulik/ldsc#183]
Hi Everyone 

I am posting this because during my Partitioned heritability analysis with the CNS sample files provided by the authors, I had an IOError. 
The following was the full details. 
./ldsc.py
 --h2 BMI.sumstats.gz 
--w-ld-chr /Users/xinyuanzhang/ldsc/weights_hm3_no_hla/weights. 
--ref-ld-chr Users/xinyuanzhang/ldsc/CNS_ldscore/CNS.,Users/xinyuanzhang/ldsc/baseline_phase1/baseline. --overlap-annot 
--frqfile-chr Users/xinyuanzhang/ldsc/1000G_frq_phase1/1000G.mac5eur. --out BMI_CNS --print-coefficient

Analysis finished at Fri Nov 22 23:04:27 2019
Total time elapsed: 1.89s
Traceback (most recent call last):
  File "ldsc.py", line 644, in <module>
    sumstats.estimate_h2(args, log)
  File "/Users/xinyuanzhang/ldsc/ldscore/sumstats.py", line 326, in estimate_h2
    args, log, args.h2)
  File "/Users/xinyuanzhang/ldsc/ldscore/sumstats.py", line 243, in _read_ld_sumstats
    ref_ld = _read_ref_ld(args, log)
  File "/Users/xinyuanzhang/ldsc/ldscore/sumstats.py", line 82, in _read_ref_ld
    'reference panel LD Score', ps.ldscore_fromlist)
  File "/Users/xinyuanzhang/ldsc/ldscore/sumstats.py", line 152, in _read_chr_split_files
    out = parsefunc(_splitp(chr_arg), _N_CHR, **kwargs)
  File "/Users/xinyuanzhang/ldsc/ldscore/parse.py", line 93, in ldscore_fromlist
    y = ldscore(fh, num)
  File "/Users/xinyuanzhang/ldsc/ldscore/parse.py", line 137, in ldscore
    s, compression = which_compression(first_fh)
  File "/Users/xinyuanzhang/ldsc/ldscore/parse.py", line 43, in which_compression
    raise IOError('Could not open {F}[./gz/bz2]'.format(F=fh))
IOError: Could not open Users/xinyuanzhang/ldsc/CNS_ldscore/CNS.1.l2.ldscore[./gz/bz2]
(ldsc) dyn899-158:ldsc xinyuanzhang$ 

Using PUBD we were able to figure out that it was actually a path issue like Hillary suggested in another issues post which reported a similar problem. [https://github.com/bulik/ldsc/issues/147](url) 
(There was another issues post that reported similar error, but I am not sure how they solved it. Person who posted said he solved it by re-calculating LD scores. Not sure the similar IOError was caused by the same issue as here... Maybe not.) 

Anyways 
I fixed my issue with simply fixed by 
./ldsc py 
ldsc.py --h2 BMI.sumstats.gz --w-ld-chr /Users/xinyuanzhang/ldsc/weights_hm3_no_hla/weights. --ref-ld-chr /Users/xinyuanzhang/ldsc/CNS_ldscore/CNS.,/Users/xinyuanzhang/ldsc/baseline_phase1/baseline. --overlap-annot --frqfile-chr /Users/xinyuanzhang/ldsc/1000G_Phase_1_frq/1000G.mac5eur. --out BMI_CNS --print-coefficient 

Notice that I added "/" before all the Users.... It was a pretty simple thing but I guess also easy to overlook. Anyways. Hope this helps other who encounter similar issues. :)

**Comment by JackieKiewa** [comment]
My problem was:
Could not open Multi_tissue_gene_expr_1000Gv3_ldscores/GTEx.1.1.l2.ldscore[./gz/bz2]
I found that it was, as Hilary suggested in another post, because my script was not located in the folder that all the files were stored in. I thought that it was enough to provide the full path to the files mentioned in the commands. However, this file isn't mentioned in the commands - presumably it is called by another function. And since I wasn't in the right folder the file couldn't be located. I solved the problem by using 'cd /path/to/folder/with/all/files' at the beginning of the bash script.
