### ISSUE TITLE
make_annot: OverflowError: can't convert negative value to CHRPOS on recent version

### ISSUE THREAD

**Issue by kvshams** [bulik/ldsc#198]
My `ldsc` worked perfectly previously, but recently I pulled the new version and now getting error with large gene set. for eg I am getting error for the `Cahoy.control.GeneSet` as below where as `Cahoy.1.GeneSet` works perfectly fine. How to fix this
```
python /home/svellari/ldsc/make_annot.py --gene-set-file Cahoy_1000Gv3_ldscores/Cahoy.control.GeneSet --gene-coord-file  ENSG_coord.txt --windowsize 100000 --bimfile 1000G_EUR_Phase3_plink/1000G.EUR.QC.1.bim --annot-file cahoy.control.1.annot.gz

making gene set bed file
Traceback (most recent call last):
  File "/home/svellari/ldsc/make_annot.py", line 50, in <module>
    bed_for_annot = gene_set_to_bed(args)
  File "/home/svellari/ldsc/make_annot.py", line 17, in gene_set_to_bed
    return BedTool(iter_df).sort().merge()
  File "/home/svellari/anaconda2/envs/ldsc/lib/python2.7/site-packages/pybedtools/bedtool.py", line 583, in __init__
    fn = BedTool(iter(fn)).saveas().fn
  File "/home/svellari/anaconda2/envs/ldsc/lib/python2.7/site-packages/pybedtools/bedtool.py", line 917, in decorated
    result = method(self, *args, **kwargs)
  File "/home/svellari/anaconda2/envs/ldsc/lib/python2.7/site-packages/pybedtools/bedtool.py", line 3342, in saveas
    out_compressed=compressed,
  File "/home/svellari/anaconda2/envs/ldsc/lib/python2.7/site-packages/pybedtools/bedtool.py", line 1412, in _collapse
    for i in iterable:
  File "pybedtools/cbedtools.pyx", line 792, in pybedtools.cbedtools.IntervalIterator.__next__
  File "pybedtools/cbedtools.pyx", line 666, in pybedtools.cbedtools.create_interval_from_list
OverflowError: can't convert negative value to CHRPOS
```

**Comment by kvshams** [comment]
Thanks @wzhxu for your #199 fix. It works perfectly well by changing 
`lane 14` as you mentioned in your pull.
I am iterating @wzhxu's fix (helpful until the ldsc team merge the his pull with master)
Change `df['START'] = np.maximum(0, df['START'] - args.windowsize)` in `make_annot.py` to `df['START'] = np.maximum(1, df['START'] - args.windowsize)` . For explanation please refer #199
