### ISSUE TITLE
Error when following the tutorial

### ISSUE THREAD

**Issue by orr161** [bulik/ldsc#211]
Hello,
I am following the [partitioned heritability tutorial](https://github.com/bulik/ldsc/wiki/Partitioned-Heritability) step by step, and encounter a "FloatingPointError: invalid value encountered in sqrt" even though I work with exactly the same files as used in the tutorial. 

I work in an anaconda env with the recommended yml setting, have 96G RAM, and git pull confirms that I am up to date. 

The munge stats part worked fine, but when I run the actual analysis I get the following output:

`Beginning analysis at Wed May 20 14:12:33 2020
Reading summary statistics from /data/lab/ldsc_analysis/BMI3.sumstats.gz ...
Read summary statistics for 1040803 SNPs.
Reading reference panel LD Score from /data/lab/ldsc_analysis/baseline/baseline$
[1-22] ...
Read reference panel LD Scores for 1189907 SNPs.
Removing partitioned LD Scores with zero variance.
Reading regression weight LD Score from /data/lab/ldsc_analysis/weights_hm3_no_$la/weights.[1-22] ...
Read regression weight LD Scores for 1242190 SNPs.
After merging with reference panel LD, 948813 SNPs remain.
After merging with regression SNP LD, 946647 SNPs remain.
Removed 17 SNPs with chi^2 > 123.912 (946630 SNPs remain)
Traceback (most recent call last):
  File "ldsc.py", line 644, in <module>
    sumstats.estimate_h2(args, log)
  File "/data/lab/software/ldsc/ldscore/sumstats.py", line 359, in estimate_h2
    twostep=args.two_step, old_weights=old_weights)
  File "/data/lab/software/ldsc/ldscore/regressions.py", line 346, in __init__
    slow=slow, step1_ii=step1_ii, old_weights=old_weights)
  File "/data/lab/software/ldsc/ldscore/regressions.py", line 208, in __init__
    jknife = jk.LstsqJackknifeFast(x, y, n_blocks)
  File "/data/lab/software/ldsc/ldscore/jackknife.py", line 314, in __init__
    self.jknife(self.pseudovalues)
  File "/data/lab/software/ldsc/ldscore/jackknife.py", line 132, in jknife
    jknife_se = np.atleast_2d(np.sqrt(jknife_var))
FloatingPointError: invalid value encountered in sqrt

Analysis finished at Wed May 20 14:13:21 2020
Total time elapsed: 48.19s
Traceback (most recent call last):
  File "ldsc.py", line 644, in <module>
    sumstats.estimate_h2(args, log)
  File "/data/lab/software/ldsc/ldscore/sumstats.py", line 359, in estimate_h2
    twostep=args.two_step, old_weights=old_weights)
  File "/data/lab/software/ldsc/ldscore/regressions.py", line 346, in __init__
    slow=slow, step1_ii=step1_ii, old_weights=old_weights)
  File "/data/lab/software/ldsc/ldscore/regressions.py", line 208, in __init__
    jknife = jk.LstsqJackknifeFast(x, y, n_blocks)
  File "/data/lab/software/ldsc/ldscore/jackknife.py", line 314, in __init__
    self.jknife(self.pseudovalues)
  File "/data/lab/software/ldsc/ldscore/jackknife.py", line 132, in jknife
    jknife_se = np.atleast_2d(np.sqrt(jknife_var))
FloatingPointError: invalid value encountered in sqrt    `

Thank you!

**Comment by orr161** [comment]
Seems to be an issue with the env on our cluster, I tried on google cloud and it worked. Closing.
