### ISSUE TITLE
Error parsing refernce panel LD Score

### ISSUE THREAD

**Issue by dgroenewoud** [bulik/ldsc#214]
Dear all,

I am experiencing an unusual error when trying to run any kind of partitioned heritability analysis. I believe this is a bug related to the _splitp function in sumstats.py. The error occurs with the most recent version of LDSC, but not - for instance - with version 1.0.0. Note that the error does not occur when calculating univariate LD scores, calculating heritability (not partitioned) or calculating correlations. 

Example of error when running the partitioned heritability analysis with continuous annotations according to the wiki tutorial:

python /LDSC/ldsc/ldsc.py --h2 BMI.sumstats.gz --ref-ld-chr 1000G_Phase3_baselineLD_ldscores/baselineLD. --frqfile-chr 1000G_Phase3_frq/1000G.EUR.QC. --w-ld-chr 1000G_Phase3_weights_hm3_no_MHC/weights.hm3_noMHC. --overlap-annot --print-coefficients --print-delete-vals --out BMI.baselineLD

*********************************************************************
* LD Score Regression (LDSC)
* Version 1.0.1
* (C) 2014-2019 Brendan Bulik-Sullivan and Hilary Finucane
* Broad Institute of MIT and Harvard / MIT Department of Mathematics
* GNU General Public License v3
*********************************************************************
Call:
./ldsc.py \
--h2 BMI.sumstats.gz \
--ref-ld-chr 1000G_Phase3_baselineLD_ldscores/baselineLD. \
--out BMI.baselineLD \
--overlap-annot  \
--frqfile-chr 1000G_Phase3_frq/1000G.EUR.QC. \
--w-ld-chr 1000G_Phase3_weights_hm3_no_MHC/weights.hm3_noMHC. \
--print-coefficients  \
--print-delete-vals

Beginning analysis at Tue Jun  2 11:41:24 2020
Reading summary statistics from BMI.sumstats.gz ...
Read summary statistics for 1040803 SNPs.
Reading reference panel LD Score from 1000G_Phase3_baselineLD_ldscores/baselineLD.[1-22] ...
Error parsing reference panel LD Score.
Traceback (most recent call last):
  File "/LDSC/ldsc/ldsc.py", line 644, in <module>
    sumstats.estimate_h2(args, log)
  File "/LDSC/ldsc/ldscore/sumstats.py", line 329, in estimate_h2
    args, log, args.h2)
  File "/LDSC/ldsc/ldscore/sumstats.py", line 246, in _read_ld_sumstats
    ref_ld = _read_ref_ld(args, log)
  File "/LDSC/ldsc/ldscore/sumstats.py", line 85, in _read_ref_ld
    'reference panel LD Score', ps.ldscore_fromlist)
  File "/LDSC/ldsc/ldscore/sumstats.py", line 158, in _read_chr_split_files
    raise e
ValueError: No objects to concatenate

**Comment by hoholee** [comment]
I got the same issue here. Apparently the lastest commit introduced this bug: https://github.com/bulik/ldsc/commit/f431a1261833425d5944311f7f7430fbc0ea228f#commitcomment-39512444

Rolling back to a previous commit (b02f2a6c6d4c2724a7d88eca8a85c952762e8f0f) fix the issue for me.

**Comment by explodecomputer** [comment]
Hi
I see there has been activity on this issue, but just to let you know it is still failing for me - unit test results below:

```
$ nosetests -A 'not slow'
...................................................................................................EEEEEEE....E.......
```

rolling back to b02f2a6 fixes the issue

**Comment by jennymoon90** [comment]
I am experiencing the same issue today. Exact same error messages.

**Comment by hbliu** [comment]
I also got the same error even after changing several baseline files.
