### ISSUE TITLE
LD score regression trait correlation ERROR: FloatingPointError: invalid value encountered in sqrt

### ISSUE THREAD

**Issue by guiyuanyuan123** [bulik/ldsc#220]
Hello,
  I have been trying so many times to reformat Summary Statistics and measure -rg between two GWAS summary stats, but I meet two errors :

[1]  converted my summary statistics
*********************************************************************
Call: 
./munge_sumstats.py \
--out test \
--merge-alleles w_hm3.snplist \
--N 2746.0 \
--sumstats diagnosis.assoc.logistic_summary 

Interpreting column names as follows:
INFO:	INFO score (imputation quality; higher --> better imputation)
A1:	        Allele 1, interpreted as ref allele for signed sumstat.
P:	        p-Value
BETA:	[linear/logistic] regression coefficient (0 --> no effect; above 0 --> A1 is trait/risk increasing)
A2:	        Allele 2, interpreted as non-ref allele for signed sumstat.
SNP:	Variant ID (e.g., rs number)

Reading list of SNPs for allele merge from w_hm3.snplist
Read 1217311 SNPs for allele merge.
Reading sumstats from diagnosis.assoc.logistic_summary into memory 5000000 SNPs at a time.

>>>>  Then this program ran for ~ 4 hours , no error message was printed, and the test.log file was 0.  <<<<

[2] I manually matched with w_hm3.snplist. Estimated Heritability, Genetic Correlation:
1)
*********************************************************************
Call: 
./ldsc.py \
--ref-ld-chr eur_w_ld_chr/ \
--out diagnosis_quantity \
--rg flipgood_qc_EUR_final_diagnosis.assoc.logistic.sumstats.gz,flipgood_qc_EUR_final_quantity.assoc.linear.sumstats.gz \
--w-ld-chr eur_w_ld_chr/ 

Beginning analysis at Thu Jun 18 18:20:21 2020
Reading summary statistics from flipgood_qc_EUR_final_diagnosis.assoc.logistic.sumstats.gz ...
Read summary statistics for 566432 SNPs.
Reading reference panel LD Score from eur_w_ld_chr/[1-22] ...
Read reference panel LD Scores for 1290028 SNPs.
Removing partitioned LD Scores with zero variance.
Reading regression weight LD Score from eur_w_ld_chr/[1-22] ...
Read regression weight LD Scores for 1290028 SNPs.
After merging with reference panel LD, 563824 SNPs remain.
After merging with regression SNP LD, 563824 SNPs remain.
Computing rg for phenotype 2/2
Reading summary statistics from flipgood_qc_EUR_final_quantity.assoc.linear.sumstats.gz ...
Read summary statistics for 566432 SNPs.
After merging with summary statistics, 563824 SNPs remain.
563824 SNPs with valid alleles.
ERROR computing rg for phenotype 2/2, from file flipgood_qc_EUR_final_quantity.assoc.linear.sumstats.gz.
Traceback (most recent call last):
  File "/export/home/guiyuanyuan/tools/ldsc/ldscore/sumstats.py", line 410, in estimate_rg
    rghat = _rg(loop, args, log, M_annot, ref_ld_cnames, w_ld_cname, i)
  File "/export/home/guiyuanyuan/tools/ldsc/ldscore/sumstats.py", line 539, in _rg
    intercept_gencov=intercepts[2], n_blocks=n_blocks, twostep=args.two_step)
  File "/export/home/guiyuanyuan/tools/ldsc/ldscore/regressions.py", line 705, in __init__
    np.multiply(hsq1.tot_delete_values, hsq2.tot_delete_values))
FloatingPointError: invalid value encountered in sqrt

Summary of Genetic Correlation Results
p1                          p2  rg  se   z   p h2_obs h2_obs_se h2_int h2_int_se gcov_int gcov_int_se
flipgood_qc_EUR_final_diagnosis.assoc.logistic.sumstats.gz  flipgood_qc_EUR_final_quantity.assoc.linear.sumstats.gz  NA  NA  NA  NA     NA        NA     NA        NA   

>>>And I looked into the univariate ldsc results for each trait:
2)
*********************************************************************
Call: 
./ldsc.py \
--h2 flipgood_qc_EUR_final_diagnosis.assoc.logistic.sumstats.gz \
--ref-ld-chr eur_w_ld_chr/ \
--out diagnosis_h2 \
--w-ld-chr eur_w_ld_chr/ 

Beginning analysis at Thu Jun 18 21:05:33 2020
Reading summary statistics from flipgood_qc_EUR_final_diagnosis.assoc.logistic.sumstats.gz ...
Read summary statistics for 566432 SNPs.
Reading reference panel LD Score from eur_w_ld_chr/[1-22] ...
Read reference panel LD Scores for 1290028 SNPs.
Removing partitioned LD Scores with zero variance.
Reading regression weight LD Score from eur_w_ld_chr/[1-22] ...
Read regression weight LD Scores for 1290028 SNPs.
After merging with reference panel LD, 563824 SNPs remain.
After merging with regression SNP LD, 563824 SNPs remain.
Using two-step estimator with cutoff at 30.
Total Observed scale h2: 0.0454 (0.2285)
Lambda GC: 1.0618
Mean Chi^2: 1.0624
Intercept: 1.0596 (0.0095)
Ratio: 0.9547 (0.153)
*********************************************************************
Call: 
./ldsc.py \
--h2 flipgood_qc_EUR_final_quantity.assoc.linear.sumstats.gz \
--ref-ld-chr eur_w_ld_chr/ \
--out quality_h2 \
--w-ld-chr eur_w_ld_chr/ 
Using two-step estimator with cutoff at 30.
Total Observed scale h2: 0.2519 (0.2173)
Lambda GC: 1.0527
Mean Chi^2: 1.0497
Intercept: 1.0343 (0.0084)
Ratio: 0.6902 (0.1683)

3)
I try to estimate hg for another trait A.sumstats.gz , *diagnosis.assoc.logistic.sumstats.gz ///A.sumstats.gz ,quantity.assoc.linear.sumstats.gz
3-1:--rg A.sumstats.gz,flipgood_qc_EUR_final_diagnosis.assoc.logistic.sumstats.gz

Heritability of phenotype 1
---------------------------
Total Observed scale h2: 0.2373 (0.0184)
Lambda GC: 1.2731
Mean Chi^2: 1.3318
Intercept: 1.0427 (0.0146)
Ratio: 0.1287 (0.0441)

Heritability of phenotype 2/2
-----------------------------
Total Observed scale h2: 0.2971 (0.2489)
Lambda GC: 1.0588
Mean Chi^2: 1.0646
Intercept: 1.0458 (0.0117)
Ratio: 0.7092 (0.1805)

Genetic Covariance
------------------
Total Observed scale gencov: 0.0104 (0.046)
Mean z1*z2: 0.0079
Intercept: 0.0056 (0.0086)

Genetic Correlation
-------------------
Genetic Correlation: 0.039 (0.1764)
Z-score: 0.2212
P: 0.8249

Summary of Genetic Correlation Results
p1                                                                    p2     rg      se       z       p  h2_obs  h2_obs_se  h2_int  h2_int_se  gcov_int  gcov_int_se
adhd_eur_jun2017.sumstats.gz  ../LD_eur/flipgood_qc_EUR_final_diagnosis.assoc.logistic.sumstats.gz  0.039  0.1764  0.2212  0.8249  0.2971     0.2489  1.0458     0.0117    0.0056       0.0086

3-2:--rg A.sumstats.gz, flipgood_qc_EUR_final_quantity.assoc.linear.sumstats.gz
Heritability of phenotype 1
---------------------------
Total Observed scale h2: 0.2373 (0.0184)
Lambda GC: 1.2731
Mean Chi^2: 1.3318
Intercept: 1.0427 (0.0146)
Ratio: 0.1287 (0.0441)

Heritability of phenotype 2/2
-----------------------------
Total Observed scale h2: 0.5157 (0.2456)
Lambda GC: 1.0527
Mean Chi^2: 1.0515
Intercept: 1.0196 (0.0106)
Ratio: 0.3803 (0.2049)

Genetic Covariance
------------------
Total Observed scale gencov: -0.0033 (0.0429)
Mean z1*z2: 0.0054
Intercept: 0.007 (0.0081)

Genetic Correlation
-------------------
Genetic Correlation: -0.0093 (0.1238)
Z-score: -0.0755
P: 0.9399

Summary of Genetic Correlation Results
p1                                                                 p2      rg      se       z       p  h2_obs  h2_obs_se  h2_int  h2_int_se  gcov_int  gcov_int_se
adhd_eur_jun2017.sumstats.gz  ../LD_eur/flipgood_qc_EUR_final_quantity.assoc.linear.sumstats.gz -0.0093  0.1238 -0.0755  0.9399  0.5157     0.2456  1.0196     0.0106     0.

That is ok.

Can anyone help me why and what I can do?

Many Thanks,
Yuanyuan

**Comment by albert-ying** [comment]
I meet same error here while estimating rg
"FloatingPointError: invalid value encountered in sqrt" and
"    c = hsq * N / M
FloatingPointError: invalid value encountered in multiply"
