### ISSUE TITLE
Partitioned heritability: Error parsing reference panel LD Score.

### ISSUE THREAD

**Issue by geneticsmcgill** [bulik/ldsc#223]
Hi there,  I keep getting an error for partitioned heritability. I've tried multiple different combinations of files (including the suggested ones in the tutorial) and with or without merging with hm3 dataset prior. Any help would be appreciated. 

Error below: 

Call:
./ldsc.py \
--h2 munged.rsid.filtered.merged_METAANALYSIS.ETGWAS.inclUKBB_2020-06-16.sumstats.gz \
--ref-ld-chr ./1000G_Phase3_baselineLD_v2.2_ldscores/baselineLD. \
--out partictionedh2.munged.hm3.rsid.filtered.merged_METAANALYSIS.ETGWAS.inclUKBB_2020-06-16_ldhub.txt.sumstats \
--overlap-annot  \
--frqfile-chr ./plink_files/1000G.EUR.hg38. \
--w-ld-chr weights/weights.hm3_noMHC.

Beginning analysis at Mon Jun 22 19:54:15 2020
Reading summary statistics from munged.rsid.filtered.merged_METAANALYSIS.ETGWAS.inclUKBB_2020-06-16.sumstats.gz ...
Read summary statistics for 5850543 SNPs.
Reading reference panel LD Score from ./1000G_Phase3_baselineLD_v2.2_ldscores/baselineLD.[1-22] ...
Error parsing reference panel LD Score.
Traceback (most recent call last):
  File "./ldsc.py", line 644, in <module>
    sumstats.estimate_h2(args, log)
  File "/Users/cl/ldsc/ldscore/sumstats.py", line 329, in estimate_h2
    args, log, args.h2)
  File "/Users/cl/ldsc/ldscore/sumstats.py", line 246, in _read_ld_sumstats
    ref_ld = _read_ref_ld(args, log)
  File "/Users/cl/ldsc/ldscore/sumstats.py", line 85, in _read_ref_ld
    'reference panel LD Score', ps.ldscore_fromlist)
  File "/Users/cl/ldsc/ldscore/sumstats.py", line 158, in _read_chr_split_files
    raise e
ValueError: No objects to concatenate

Analysis finished at Mon Jun 22 19:54:25 2020
Total time elapsed: 10.02s
Traceback (most recent call last):
  File "./ldsc.py", line 644, in <module>
    sumstats.estimate_h2(args, log)
  File "/Users/cl/ldsc/ldscore/sumstats.py", line 329, in estimate_h2
    args, log, args.h2)
  File "/Users/cl/ldsc/ldscore/sumstats.py", line 246, in _read_ld_sumstats
    ref_ld = _read_ref_ld(args, log)
  File "/Users/cl/ldsc/ldscore/sumstats.py", line 85, in _read_ref_ld
    'reference panel LD Score', ps.ldscore_fromlist)
  File "/Users/cl/ldsc/ldscore/sumstats.py", line 158, in _read_chr_split_files
    raise e
ValueError: No objects to concatenate

**Comment by futurologist** [comment]
Hi, I also have the same problem. For me, the current version of ldsc produces exactly the same error when running the tutorial examples. Basically, it works for heritability and genetic correlation, but fails the tutorial suggested tests for partitioned heritability:  

Beginning analysis at Fri Jun 26 15:32:41 2020
The frequency file is unnecessary and is being ignored.
Reading summary statistics from /home/LDSC_work/outs_part_herit_sumstats/BMI.sumstats.gz ...
Read summary statistics for 1040803 SNPs.
Reading reference panel LD Score from /home/LDSC_work/dwnlds_partition_herit/baseline/baseline.[1-22] ...
Error parsing reference panel LD Score.
Traceback (most recent call last):
  File "/home/ldsc/ldsc.py", line 644, in <module>
    sumstats.estimate_h2(args, log)
  File "/home/ldsc/ldscore/sumstats.py", line 329, in estimate_h2
    args, log, args.h2)
  File "/home/ldsc/ldscore/sumstats.py", line 246, in _read_ld_sumstats
    ref_ld = _read_ref_ld(args, log)
  File "/home/ldsc/ldscore/sumstats.py", line 85, in _read_ref_ld
    'reference panel LD Score', ps.ldscore_fromlist)
  File "/home/ldsc/ldscore/sumstats.py", line 158, in _read_chr_split_files
    raise e
ValueError: No objects to concatenate

Is there a way to fix this?

**Comment by annashcherbina** [comment]
Same issue here on tutorial datasets and my own data -- confirmed that reverting to b02f2a6 fixes the problem.

**Comment by rodrigoduarte88** [comment]
`git checkout b02f2a6` did the work for me! Thanks!
