### ISSUE TITLE
ValueError: LD Scores for concatenation must have identical SNP columns.

### ISSUE THREAD

**Issue by easwaranramamurthy** [bulik/ldsc#233]
Hi,

I'm running into the following error when attempting to run LDSC to get cell type-specific heritability estimates for 3 cell types:

```
*********************************************************************
* LD Score Regression (LDSC)
* Version 1.0.0
* (C) 2014-2015 Brendan Bulik-Sullivan and Hilary Finucane
* Broad Institute of MIT and Harvard / MIT Department of Mathematics
* GNU General Public License v3
*********************************************************************
Call: 
./ldsc.py \
--h2 X_GWAS.sumstats.gz \
--ref-ld-chr peaks_1.,peaks_2.,peaks_3.,merge_of_peaks_1_2_and_3.,1000G_Phase3_baseline/baseline. \
--out X_gwas.heritability \
--overlap-annot  \
--frqfile-chr 1000G_Phase3_frq/1000G.EUR.QC. \
--w-ld-chr weights_hm3_no_hla/weights. \
--print-coefficients  

Beginning analysis at Tue Jul 28 19:43:36 2020
Reading summary statistics from X_GWAS.sumstats.gz ...
Read summary statistics for 1146109 SNPs.
Reading reference panel LD Score from peaks_1.,peaks_2.,peaks_3.,merge_of_peaks_1_2_and_3.,1000G_Phase3_baseline/baseline.[1-22] ...
Error parsing reference panel LD Score.
Traceback (most recent call last):
  File "/path/to/ldsc/ldsc.py", line 644, in <module>
    sumstats.estimate_h2(args, log)
  File "/path/to/ldsc/ldscore/sumstats.py", line 326, in estimate_h2
    args, log, args.h2)
  File "/path/to/ldsc/ldscore/sumstats.py", line 243, in _read_ld_sumstats
    ref_ld = _read_ref_ld(args, log)
  File "/path/to/ldsc/ldscore/sumstats.py", line 82, in _read_ref_ld
    'reference panel LD Score', ps.ldscore_fromlist)
  File "/path/to/ldsc/ldscore/sumstats.py", line 155, in _read_chr_split_files
    raise e
ValueError: LD Scores for concatenation must have identical SNP columns.

Analysis finished at Tue Jul 28 19:44:30 2020
Total time elapsed: 53.92s
```

I went through the source code to see what triggers the error and found that it is thrown due to an unequal number of SNPs in the different l2.ldscores.gz files that I input to the tool. 

For example, when I check the l2.ldscores.gz files for chromosome 1, I notice that peaks_1.1.l2.ldscores.gz,peaks_2.1.l2.ldscores.gz,peaks_3.1.l2.ldscores.gz,merge_of_peaks_1_2_and_3.1.l2.ldscores.gz all have information for 98691 SNPs (lines). However, the 1000G_Phase3_baseline/baseline.1.l2.ldscores.gz file has information for a slightly different set of 98643 SNPs (lines).

I would appreciate any pointers as to how to best resolve this issue.

For reference, here is how I created the foreground annotations for peaks_1., peaks_2. and peaks_3. and merge_of_peaks_1_2_and_3.

```
for i in {1..22}
do 
python /path/to/ldsc/make_annot.py --bed-file peaks_1.bed --bimfile 1000G_EUR_Phase3_plink/1000G.EUR.QC.${i}.bim --annot-file peaks_1.${i}.annot

python /path/to/ldsc/ldsc.py --l2 --bfile 1000G_EUR_Phase3_plink/1000G.EUR.QC.${i} --ld-wind-cm 1 --annot peaks_i.${i}.annot --thin-annot --out peaks_1.${i} --print-snps hapmap3_snps/hm.${i}.snp

done
```

**Comment by easwaranramamurthy** [comment]
Hi,

Just checking, are the Github issues being actively resolved by the ldsc authors? Is there another forum which is more appropriate for raising these issues?

Best,
Easwaran

**Comment by gbloeb** [comment]
@easwaranramamurthy Did you figure out a way around this?  Seems the problem is that the baseline model is built with a different snp set that does not seem to be accessible. Thanks for any pointers.

**Comment by easwaranramamurthy** [comment]
@gbloeb yes, I think you're right. I do have a workaround but it was a little tedious. Unfortunately, it involves regenerating the baseline model annotations from scratch starting from the 82 bed files provided here: https://storage.googleapis.com/broad-alkesgroup-public/LDSCORE/baselineLD_v2.2_bedfiles.tgz

I did this using the same commands that I used to generate the annotations and LD scores for the foregrounds:

```
wget https://storage.googleapis.com/broad-alkesgroup-public/LDSCORE/baselineLD_v2.2_bedfiles.tgz
tar -xzvf baselineLD_v2.2_bedfiles.tgz
cd baselineLD_v2.2_bedfiles


for bedfile in *.bed
do
fileprefix=${bedfile%".bed"}
for chromnumber in {1..22}
do
python /path/to/ldsc/make_annot.py --bed-file ${bedfile} --bimfile /path/to/1000G_EUR_Phase3_plink/1000G.EUR.QC.${chromnumber}.bim --annot-file ${fileprefix}.${chromnumber}.annot

python /path/to/ldsc/ldsc.py --l2 --bfile /path/to/1000G_EUR_Phase3_plink/1000G.EUR.QC.${chromnumber} --ld-wind-cm 1 --annot ${fileprefix}.${chromnumber}.annot --thin-annot --out ${fileprefix}.${chromnumber} --print-snps /path/to/hapmap3_snps/hm.${chromnumber}.snp
done
done
```

This will run every step in series, so it will be really slow. Parallelizing on the chromosomes and/or the 82 bed files will help speed things up.

Best,
Easwaran

**Comment by aMattScientist** [comment]
The baseline annotations were generated using SNPs from 'list.txt' (https://storage.googleapis.com/broad-alkesgroup-public/LDSCORE/list.txt) instead of the hapmap3_snps 

--print-snps /n/groups/price/ldsc/reference_files/1000G_EUR_Phase3/list.txt

You can regenerate your custom annotations on this SNP set and it will be compatible!

**Comment by sherifgerges** [comment]
Would you happen to know where I can find the corresponding SNP list for the EAS 1000G ldscores?

**Comment by fanying2015** [comment]
> @gbloeb yes, I think you're right. I do have a workaround but it was a little tedious. Unfortunately, it involves regenerating the baseline model annotations from scratch starting from the 82 bed files provided here: https://storage.googleapis.com/broad-alkesgroup-public/LDSCORE/baselineLD_v2.2_bedfiles.tgz
> 
> I did this using the same commands that I used to generate the annotations and LD scores for the foregrounds:
> 
> ```
> wget https://storage.googleapis.com/broad-alkesgroup-public/LDSCORE/baselineLD_v2.2_bedfiles.tgz
> tar -xzvf baselineLD_v2.2_bedfiles.tgz
> cd baselineLD_v2.2_bedfiles
> 
> 
> for bedfile in *.bed
> do
> fileprefix=${bedfile%".bed"}
> for chromnumber in {1..22}
> do
> python /path/to/ldsc/make_annot.py --bed-file ${bedfile} --bimfile /path/to/1000G_EUR_Phase3_plink/1000G.EUR.QC.${chromnumber}.bim --annot-file ${fileprefix}.${chromnumber}.annot
> 
> python /path/to/ldsc/ldsc.py --l2 --bfile /path/to/1000G_EUR_Phase3_plink/1000G.EUR.QC.${chromnumber} --ld-wind-cm 1 --annot ${fileprefix}.${chromnumber}.annot --thin-annot --out ${fileprefix}.${chromnumber} --print-snps /path/to/hapmap3_snps/hm.${chromnumber}.snp
> done
> done
> ```
> 
> This will run every step in series, so it will be really slow. Parallelizing on the chromosomes and/or the 82 bed files will help speed things up.
> 
> Best,
> Easwaran

Hi,

Thank you for the discussion. I'm wondering how you define the 'base' annotation? It's supposed to a category containing all SNP. I found the category in the final ldscore (baseL2), but can't find the corresponding bed file. 

Thank you!


Best,
Fanying

**Comment by ashwini-kr-sharma** [comment]
@easwaranramamurthy I was wondering how would you then merge the baseline model annotations for each of the 86 bed files into one file per chromosomes like in 1000G_Phase3_baselineLD_v2.2_ldscores.tgz ?

**Comment by mohammedmsk** [comment]
> The baseline annotations were generated using SNPs from 'list.txt' (https://storage.googleapis.com/broad-alkesgroup-public/LDSCORE/list.txt) instead of the hapmap3_snps
> 
> --print-snps /n/groups/price/ldsc/reference_files/1000G_EUR_Phase3/list.txt
> 
> You can regenerate your custom annotations on this SNP set and it will be compatible!

Where exactly is this file in the new Google cloud bucket?

**Comment by markphillippebworth** [comment]
The files are now found on Zenodo instead of Google bucket. 
https://zenodo.org/records/8292725
