### ISSUE TITLE
estimate_rg (FloatingPointError: invalid value encountered in sqrt)

### ISSUE THREAD

**Issue by hanson1234** [bulik/ldsc#241]
I wanted to estimate genetic correlation between two binary trait, The summary statistics beta and se are based logistic regression. Their Zscores range are [-8.881,7.614], and [-4.398,5.029]. When I used the following command line, the rg will produce the errors. 
    Can you give me some advice on how to fix them? Thanks!
    Best regards!
Hanson

* LD Score Regression (LDSC)
* Version 1.0.0
* (C) 2014-2015 Brendan Bulik-Sullivan and Hilary Finucane
* Broad Institute of MIT and Harvard / MIT Department of Mathematics
* GNU General Public License v3
*********************************************************************
Call: 
./ldsc.py \
--ref-ld-chr eur_w_ld_chr/ \
--out ./pgc3_genderAge_BiploarStatus_regenie \
--rg ./daner_bip_pgc3_nm_Subcolumn.w_hm3.sumstats.gz,./test_bin_out_firth_EUR_2var_BT_Status_Bipolar.regenie_subcol.w_hm3.sumstats.gz \
--w-ld-chr eur_w_ld_chr/ 

Beginning analysis at Mon Sep 28 16:17:44 2020
Reading summary statistics from 
./daner_bip_pgc3_nm_Subcolumn.w_hm3.sumstats.gz ...
Read summary statistics for 1090822 SNPs.
Reading reference panel LD Score from eur_w_ld_chr/[1-22] ...
Read reference panel LD Scores for 1290028 SNPs.
Removing partitioned LD Scores with zero variance.
Reading regression weight LD Score from eur_w_ld_chr/[1-22] ...
Read regression weight LD Scores for 1290028 SNPs.
After merging with reference panel LD, 1086428 SNPs remain.
After merging with regression SNP LD, 1086428 SNPs remain.
Computing rg for phenotype 2/2
Reading summary statistics from ./test_bin_out_firth_EUR_2var_BT_Status_Bipolar.regenie_subcol.w_hm3.sumstats.gz ...
Read summary statistics for 1217311 SNPs.
After merging with summary statistics, 1086428 SNPs remain.
786449 SNPs with valid alleles.
ERROR computing rg for phenotype 2/2, from file /home/hanl3/cmc/BioVU_Mega/scratch/GWAS_Analysis/test_bin_out_firth_EUR_2var_BT_Status_Bipolar.regenie_subcol.w_hm3.sumstats.gz.
Traceback (most recent call last):
  File "/gpfs52/data/ruderferlab/software/ldsc/ldscore/sumstats.py", line 410, in estimate_rg
    rghat = _rg(loop, args, log, M_annot, ref_ld_cnames, w_ld_cname, i)
  File "/gpfs52/data/ruderferlab/software/ldsc/ldscore/sumstats.py", line 537, in _rg
    intercept_gencov=intercepts[2], n_blocks=n_blocks, twostep=args.two_step)
  File "/gpfs52/data/ruderferlab/software/ldsc/ldscore/regressions.py", line 705, in __init__
    np.multiply(hsq1.tot_delete_values, hsq2.tot_delete_values))
FloatingPointError: invalid value encountered in sqrt

Summary of Genetic Correlation Results
p1                                                                                                                               p2  rg  se   z   p h2_obs h2_obs_se h2_int h2_int_se gcov_int gcov_int_se
/home/hanl3/cmc/BioVU_Mega/scratch/GWAS_Analysis/daner_bip_pgc3_nm_Subcolumn.w_hm3.sumstats.gz  /home/hanl3/cmc/BioVU_Mega/scratch/GWAS_Analysis/test_bin_out_firth_EUR_2var_BT_Status_Bipolar.regenie_subcol.w_hm3.sumstats.gz  NA  NA  NA  NA     NA        NA     NA        NA       NA          NA

Analysis finished at Mon Sep 28 16:17:57 2020
Total time elapsed: 13.18s

**Comment by samreenzafer** [comment]
Did you ever figure out the problem to this? I'm getting the same issue. I'm calculating the genetic correlation of our trait against some of the published UKBB_LDSC sumstats provided by NealeLab at https://nealelab.github.io/UKBB_ldsc/downloads.html#ldsc_sumstat_files 
Not all of them give this error though.

**Comment by Steven-Shixq** [comment]
I got the same error

**Comment by igumnov-daniel** [comment]
Same

**Comment by guarelin** [comment]
Same :(

**Comment by aksarkar** [comment]
@Steven-Shixq @igumnov-daniel @guarelin The error happens because at least one of the jacknife estimates of heritability of at least one of the phenotypes is negative. 

That would indicate that the heritability is not statistically distinguishable from 0, and that the genetic correlation cannot be reliably estimated.
