### ISSUE TITLE
ValueError: Columns ['P'] are expected to be numeric

### ISSUE THREAD

**Issue by AmmyDK** [bulik/ldsc#242]
Dear LDSC TEAM,

I have run ldsc many times, but tonight I have a new error, says my p-value is numeric, I am not sure what is that meaning, and how can I change my input data formate? 

And you can see this following:

ERROR converting summary statistics:

Traceback (most recent call last):
  File "./munge_sumstats.py", line 686, in munge_sumstats
    dat = parse_dat(dat_gen, cname_translation, merge_alleles, log, args)
  File "./munge_sumstats.py", line 249, in parse_dat
    raise ValueError('Columns {} are expected to be numeric'.format(wrong_types))
ValueError: Columns ['P'] are expected to be numeric

Thank you so much.

**Comment by senthil-th** [comment]
Check this https://groups.google.com/g/ldsc_users/c/VScICJ_XRrQ/m/wGTphZa3BgAJ
and this https://groups.google.com/forum/#!searchin/ldsc_users/dtype%7Csort:date/ldsc_users/JcrWYLRJm_s/D-jWSF7oBwAJ

I had the same error and it is related to having p-values <1e-300 or odds ratio> 1e300
