### ISSUE TITLE
Error for ldsc.py

### ISSUE THREAD

**Issue by xiangboyulan** [bulik/ldsc#243]
Hi,
(ldsc13) [huawei@localhost DTI]$ /home/huawei/xb/mri_major_psychi/ldsc_master/ldsc.py --rg test.sumstats.gz,anhed.sumsta                                                                                                                     ts.gz --ref-ld-chr /home/huawei/xb/mri_major_psychi/ldsc/eur_w_ld_chr/ --out test_new --w-ld-chr /home/huawei/xb/mri_maj                                                                                                                     or_psychi/ldsc/eur_w_ld_chr/;
*********************************************************************
* LD Score Regression (LDSC)
* Version 1.0.1
* (C) 2014-2019 Brendan Bulik-Sullivan and Hilary Finucane
* Broad Institute of MIT and Harvard / MIT Department of Mathematics
* GNU General Public License v3
*********************************************************************
Call:
./ldsc.py \
--ref-ld-chr /home/huawei/xb/mri_major_psychi/ldsc/eur_w_ld_chr/ \
--out test_new \
--rg test.sumstats.gz,anhed.sumstats.gz \
--w-ld-chr /home/huawei/xb/mri_major_psychi/ldsc/eur_w_ld_chr/

Beginning analysis at Tue Nov  3 17:15:59 2020
Reading summary statistics from test.sumstats.gz ...
Exception pandas.parser.CParserError: CParserError("Error tokenizing data. C error: Calling read(nbytes) on source faile                                                                                                                     d. Try engine='python'.",) in 'pandas.parser.TextReader._tokenize_rows' ignored
Traceback (most recent call last):
  File "/home/huawei/xb/mri_major_psychi/ldsc_master/ldsc.py", line 642, in <module>
    sumstats.estimate_rg(args, log)
  File "/home/huawei/xb/mri_major_psychi/ldsc_master/ldscore/sumstats.py", line 397, in estimate_rg
    alleles=True, dropna=True)
  File "/home/huawei/xb/mri_major_psychi/ldsc_master/ldscore/sumstats.py", line 242, in _read_ld_sumstats
    sumstats = _read_sumstats(args, log, fh, alleles=alleles, dropna=dropna)
  File "/home/huawei/xb/mri_major_psychi/ldsc_master/ldscore/sumstats.py", line 163, in _read_sumstats
    sumstats = ps.sumstats(fh, alleles=alleles, dropna=dropna)
  File "/home/huawei/xb/mri_major_psychi/ldsc_master/ldscore/parse.py", line 91, in sumstats
    raise ValueError('Improperly formatted sumstats file: ' + str(e.args))
ValueError: Improperly formatted sumstats file: ('No columns to parse from file',)

**Comment by awilliamson10** [comment]
I'm also experiencing this same issue following successful munge of my two summary sets. Is anyone aware of a solution?

**Comment by hubersn1998** [comment]
Does anybody already know a solution for this issue? I'm also experiencing it. 

Update: I found out that I was working with the wrong versions of some of the modules in the conda environment. I overcame the issue by updating the modules.

**Comment by pebblets** [comment]
> Does anybody already know a solution for this issue? I'm also experiencing it.
> 
> Update: I found out that I was working with the wrong versions of some of the modules in the conda environment. I overcame the issue by updating the modules.

I'm also experiencing this same issue. Would you mind sharing your version of modules in the conda environment or .yml file ? Thanks!

**Comment by tobiaswolfram** [comment]
I had this problem when I was working through the tutorial for rG estimation. It turned out that GCTA saved the output as .sumstat.gz, but the files are actually just in .sumstat format. In this respect, it worked to adjust the file extension by removing the .gz.
