### ISSUE TITLE
Memory Error for Linkage disequilibrium with annotation

### ISSUE THREAD

**Issue by lmangnier** [bulik/ldsc#263]
Hi, 

Actually I tried to launch Linkage disequilibrium computation of 1000 Genomes reference panel with my own annotation data. However I had several times a memory Error from corSumVarBlocks function even if I launch the script on chromosome 22. 
Even if I configure the server with 300GB RAM or decrease the chunk size parameter to 500 000, I have this error. I wonder, if I did something wrong. 

Here my command on chromosome 22 and the result output by ldsc.py:

python ../../ldsc/ldsc.py --l2 --bfile chr22_with_cms --ld-wind-cm 1 --annot NEU_Enh_ABC_chr22.annot.gz --thin-annot --out chr22_NEU_Enh_ABC --print-snps hm.22.snps

Call: 
./ldsc.py \
--chunk-size 500000 \
--print-snps hm.22.snps \
--ld-wind-cm 1.0 \
--out chr22_NEU_Enh_ABC \
--bfile chr22_with_cms \
--thin-annot  \
--annot NEU_Enh_ABC_chr22.annot.gz \
--l2  

Beginning analysis at Thu Jan 21 15:53:01 2021
Read list of 1103547 SNPs from chr22_with_cms.bim
Read 1 annotations for 1103589 SNPs from NEU_Enh_ABC_chr22.annot.gz
Read list of 2504 individuals from chr22_with_cms.fam
Reading genotypes from chr22_with_cms.bed
After filtering, 1099474 SNPs remain
Estimating LD Score.
Traceback (most recent call last):
  File "../../ldsc/ldsc.py", line 620, in <module>
    ldscore(args, log)
  File "../../ldsc/ldsc.py", line 316, in ldscore
    lN = geno_array.ldScoreVarBlocks(block_left, args.chunk_size, annot=annot_matrix)
  File "/project/6000443/loicm/Hi-C/ldsc/ldscore/ldscore.py", line 125, in ldScoreVarBlocks
    return self.__corSumVarBlocks__(block_left, c, func, snp_getter, annot)
  File "/project/6000443/loicm/Hi-C/ldsc/ldscore/ldscore.py", line 190, in __corSumVarBlocks__
    rfuncAB = np.zeros((b, c))
MemoryError

Any insights are welcome. 

Loic

**Comment by lmangnier** [comment]
Actually, I solved this issue by filter only on relevant SNPs in my summary statistic file with PLINK. 
The code turns well now. 

Loic
