### ISSUE TITLE
While calculating LD scores over annotation file got IndexError: positional indexers out of bounds

### ISSUE THREAD

**Issue by RKeener** [bulik/ldsc#279]
While working in the ldsc environment, I was running the example code and files for computing LD scores over an annotation file, as outlined in part 2 of Partitioned LD scores in the LD score estimation tutorial. 

I looked through previously reported issues and could not find this specific Index Error: positional indexers are out of bounds. Some googling suggests this is a pandas issue. Here is my code (exactly as in the wiki) and the full error message:

```
$ python /work-zfs/abattle4/rebecca/ldsc/ldsc.py --l2 --bfile 1000G_EUR_Phase3_plink/1000G.EUR.QC.22 --ld-wind-cm 1 --annot Brain_DPC_H3K27ac.annot.gz --out Brain_DPC_H3K27ac --print-snps hm.22.snp
*********************************************************************
* LD Score Regression (LDSC)
* Version 1.0.1
* (C) 2014-2019 Brendan Bulik-Sullivan and Hilary Finucane
* Broad Institute of MIT and Harvard / MIT Department of Mathematics
* GNU General Public License v3
*********************************************************************
Call: 
./ldsc.py \
--print-snps hm.22.snp \
--ld-wind-cm 1.0 \
--out Brain_DPC_H3K27ac \
--bfile 1000G_EUR_Phase3_plink/1000G.EUR.QC.22 \
--annot Brain_DPC_H3K27ac.annot.gz \
--l2  

Beginning analysis at Thu Mar  4 16:57:47 2021
Read list of 141123 SNPs from 1000G_EUR_Phase3_plink/1000G.EUR.QC.22.bim
Error parsing .annot file
Traceback (most recent call last):
  File "/work-zfs/abattle4/rebecca/ldsc/ldsc.py", line 620, in <module>
    ldscore(args, log)
  File "/work-zfs/abattle4/rebecca/ldsc/ldsc.py", line 149, in ldscore
    annot = ps.AnnotFile(args.annot)
  File "/work-zfs/abattle4/rebecca/ldsc/ldscore/parse.py", line 256, in __init__
    self.__read__(fname)
  File "/work-zfs/abattle4/rebecca/ldsc/ldscore/parse.py", line 272, in __read__
    self.IDList = self.df.iloc[:, [self.__keepcol__]].astype('object')
  File "/home-4/rwalte23@jhu.edu/.conda/envs/ldsc/lib/python2.7/site-packages/pandas/core/indexing.py", line 1325, in __getitem__
    return self._getitem_tuple(key)
  File "/home-4/rwalte23@jhu.edu/.conda/envs/ldsc/lib/python2.7/site-packages/pandas/core/indexing.py", line 1662, in _getitem_tuple
    self._has_valid_tuple(tup)
  File "/home-4/rwalte23@jhu.edu/.conda/envs/ldsc/lib/python2.7/site-packages/pandas/core/indexing.py", line 189, in _has_valid_tuple
    if not self._has_valid_type(k, i):
  File "/home-4/rwalte23@jhu.edu/.conda/envs/ldsc/lib/python2.7/site-packages/pandas/core/indexing.py", line 1599, in _has_valid_type
    return self._is_valid_list_like(key, axis)
  File "/home-4/rwalte23@jhu.edu/.conda/envs/ldsc/lib/python2.7/site-packages/pandas/core/indexing.py", line 1656, in _is_valid_list_like
    raise IndexError("positional indexers are out-of-bounds")
IndexError: positional indexers are out-of-bounds

Analysis finished at Thu Mar  4 16:57:48 2021
Total time elapsed: 0.16s
Traceback (most recent call last):
  File "/work-zfs/abattle4/rebecca/ldsc/ldsc.py", line 620, in <module>
    ldscore(args, log)
  File "/work-zfs/abattle4/rebecca/ldsc/ldsc.py", line 149, in ldscore
    annot = ps.AnnotFile(args.annot)
  File "/work-zfs/abattle4/rebecca/ldsc/ldscore/parse.py", line 256, in __init__
    self.__read__(fname)
  File "/work-zfs/abattle4/rebecca/ldsc/ldscore/parse.py", line 272, in __read__
    self.IDList = self.df.iloc[:, [self.__keepcol__]].astype('object')
  File "/home-4/rwalte23@jhu.edu/.conda/envs/ldsc/lib/python2.7/site-packages/pandas/core/indexing.py", line 1325, in __getitem__
    return self._getitem_tuple(key)
  File "/home-4/rwalte23@jhu.edu/.conda/envs/ldsc/lib/python2.7/site-packages/pandas/core/indexing.py", line 1662, in _getitem_tuple
    self._has_valid_tuple(tup)
  File "/home-4/rwalte23@jhu.edu/.conda/envs/ldsc/lib/python2.7/site-packages/pandas/core/indexing.py", line 189, in _has_valid_tuple
    if not self._has_valid_type(k, i):
  File "/home-4/rwalte23@jhu.edu/.conda/envs/ldsc/lib/python2.7/site-packages/pandas/core/indexing.py", line 1599, in _has_valid_type
    return self._is_valid_list_like(key, axis)
  File "/home-4/rwalte23@jhu.edu/.conda/envs/ldsc/lib/python2.7/site-packages/pandas/core/indexing.py", line 1656, in _is_valid_list_like
    raise IndexError("positional indexers are out-of-bounds")
IndexError: positional indexers are out-of-bounds
```
I verified that my ldsc version is up to date using git pull and it reported Already up-to-date.
Here is the beginning lines of the Brain_DPC_H3K27ac.annot.gz file, since that seems to be triggering the error: 
```
$ zcat Brain_DPC_H3K27ac.annot.gz | head
ANNOT
0
0
0
0
0
0
0
0
0
```
Any help resolving this would be fantastic as I'm sure it will affect others.

**Comment by RKeener** [comment]
I realized this was caused because the make_annot.py script automatically generates thin-annot files, as you can see in the head of the annot.gz file I provided. 

I got this error because in my ldsc.py command to partition heritability I did not include the --thin-annot flag. 
Once I did, the script worked just fine.
