### ISSUE TITLE
Some results have NA values

### ISSUE THREAD

**Issue by dzimmerman-amc** [bulik/ldsc#290]
Hi there, 

I am performing a genetic correlation analysis and receive NA results for some of the traits I'm testing but works for others. This is the error I get:

_ERROR computing rg for phenotype 2/2, from file /home/expcard/Projects/GWAS_SCA/GWAS_NTR/LDSC/NEWFORMAT/Schunkert_CAD_2011.sumstats.gz.
Traceback (most recent call last):
  File "/home/expcard/Projects/GWAS_SCA/GWAS_NTR/LDSC/ldsc/ldscore/sumstats.py", line 410, in estimate_rg
    rghat = _rg(loop, args, log, M_annot, ref_ld_cnames, w_ld_cname, i)
  File "/home/expcard/Projects/GWAS_SCA/GWAS_NTR/LDSC/ldsc/ldscore/sumstats.py", line 539, in _rg
    intercept_gencov=intercepts[2], n_blocks=n_blocks, twostep=args.two_step)
  File "/home/expcard/Projects/GWAS_SCA/GWAS_NTR/LDSC/ldsc/ldscore/regressions.py", line 705, in __init__
    np.multiply(hsq1.tot_delete_values, hsq2.tot_delete_values))
FloatingPointError: invalid value encountered in sqrt_

Has anyone come across this issue? Could it be that the heritability of my own trait is too low?

Thanks!

**Comment by nrs225** [comment]
Hi.

I also have the same problem with my traits.
Running SNP heritability for each trait on its own suggests non-zero heritability for each of the traits I have.

**Trait 1 SNP Heritability:**
```
Total Liability scale h2: 0.1755 (0.0691)
Lambda GC: 0.9898
Mean Chi^2: 1.4581
Intercept: 1.0014 (0.012)
Ratio: 0.0031 (0.0261)
```

**Trait 2 SNP Heritability:**
```
Total Liability scale h2: 0.3031 (0.118)
Lambda GC: 0.9145
Mean Chi^2: 1.3808
Intercept: 0.9327 (0.015)
Ratio < 0 (usually indicates GC correction).
```

**Genetic Correlation:**
```
Reading summary statistics from Trait1.sumstats.gz ...
Read summary statistics for 1136459 SNPs.
Reading reference panel LD Score from /mnt/nfs/home/nrs225/Software/ldsc/eur_w_ld_chr/[1-22] ... (ldscore_fromlist)
Read reference panel LD Scores for 1290028 SNPs.
Removing partitioned LD Scores with zero variance.
Reading regression weight LD Score from /mnt/nfs/home/nrs225/Software/ldsc/eur_w_ld_chr/[1-22] ... (ldscore_fromlist)
Read regression weight LD Scores for 1290028 SNPs.
After merging with reference panel LD, 1130135 SNPs remain.
After merging with regression SNP LD, 1130135 SNPs remain.
Computing rg for phenotype 2/2
Reading summary statistics from Trait2.sumstats.gz ...
Read summary statistics for 1217311 SNPs.
After merging with summary statistics, 1130135 SNPs remain.
1130135 SNPs with valid alleles.
ERROR computing rg for phenotype 2/2, from file Trait2.sumstats.gz.
Traceback (most recent call last):
  File "/mnt/storage/apps/eb/software/ldsc/1.0.1-GCCcore-11.2.0/bin/ldscore/sumstats.py", line 410, in estimate_rg
    rghat = _rg(loop, args, log, M_annot, ref_ld_cnames, w_ld_cname, i)
  File "/mnt/storage/apps/eb/software/ldsc/1.0.1-GCCcore-11.2.0/bin/ldscore/sumstats.py", line 539, in _rg
    intercept_gencov=intercepts[2], n_blocks=n_blocks, twostep=args.two_step)
  File "/mnt/storage/apps/eb/software/ldsc/1.0.1-GCCcore-11.2.0/bin/ldscore/regressions.py", line 705, in __init__
    np.multiply(hsq1.tot_delete_values, hsq2.tot_delete_values))
FloatingPointError: invalid value encountered in sqrt



Summary of Genetic Correlation Results
p1                             p2  rg  se   z   p h2_obs h2_obs_se h2_int h2_int_se gcov_int gcov_int_se
Trait1.sumstats.gz  Trait2.sumstats.gz  NA  NA  NA  NA     NA        NA     NA        NA       NA          NA
```

Is there a solution to this issue?

Many thanks.

**Comment by nvice111** [comment]
Regarding the issue mentioned, the authors of LDSC have addressed this concern in their response to the query. They indicate that the problem of NAs cannot be resolved. For more details, see their reply on GitHub: https://github.com/bulik/ldsc/issues/40
