### ISSUE TITLE
munge_sumstats: --signed-sumstats error

### ISSUE THREAD

**Issue by RuochengDong** [bulik/ldsc#291]
Hi,

I am using the munge_sumstats to convert the GWAS summary stats but failed. Does anyone know how to solve this problem?

And I am using the code:
```
python munge_sumstats.py --sumstats gwas.txt --snp SNP --N-col N --a1 A1 --a2 A2 --frq freq --p p --signed-sumstats b --out gwas_formatted
```
But I got the error :
```
* LD Score Regression (LDSC)
* Version 1.0.1
* (C) 2014-2019 Brendan Bulik-Sullivan and Hilary Finucane
* Broad Institute of MIT and Harvard / MIT Department of Mathematics
* GNU General Public License v3
*********************************************************************
Call:
./munge_sumstats.py \
--signed-sumstats b \
--out AB42_gwas_formatted \
--frq freq \
--N-col N \
--a1 A1 \
--a2 A2 \
--snp SNP \
--sumstats gwas.txt \
--p p

The argument to --signed-sumstats should be column header comma number.

ERROR converting summary statistics:

Traceback (most recent call last):
  File "munge_sumstats.py", line 552, in munge_sumstats
    flag_cnames, signed_sumstat_null = parse_flag_cnames(log, args)
  File "munge_sumstats.py", line 413, in parse_flag_cnames
    cname, null_value = args.signed_sumstats.split(',')
ValueError: need more than 1 value to unpack

Conversion finished at Wed Apr 14 23:42:41 2021
Total time elapsed: 0.0s
Traceback (most recent call last):
  File "munge_sumstats.py", line 745, in <module>
    munge_sumstats(parser.parse_args(), p=True)
  File "munge_sumstats.py", line 552, in munge_sumstats
    flag_cnames, signed_sumstat_null = parse_flag_cnames(log, args)
  File "munge_sumstats.py", line 413, in parse_flag_cnames
    cname, null_value = args.signed_sumstats.split(',')
ValueError: need more than 1 value to unpack
```
Thank you.

**Comment by ghost** [comment]
RuoCheng, can you tell me how you fix it? I came across the same issue. Thanks!

**Comment by yningvu** [comment]
> RuoCheng, can you tell me how you fix it? I came across the same issue. Thanks!

You need to specify the column name and the null value separating by a comma in that flag. For example, if your effect column is beta, then the flag should be "--signed-sumstats beta,0".

**Comment by DoviniJ** [comment]
if I have OR, do I need to specify 0 or any other number?
"--signed-sumstats OR,?????".

**Comment by cyclovecqh** [comment]
> if I have OR, do I need to specify 0 or any other number? "--signed-sumstats OR,?????".

I solve this problem.
--signed-sumstats OR,1
