### ISSUE TITLE
unexpected keyword argument 'subset'

### ISSUE THREAD

**Issue by adamxm** [bulik/ldsc#30]
I ran the following command:

python ldsc.py --h2  mydata.sumstats   --ref-ld-chr eur_w_ld_chr/ --w-ld-chr eur_w_ld_chr/ --out myresults_ldsc

And got the following error:

Traceback (most recent call last):
  File "ldsc.py", line 617, in <module>
    sumstats.estimate_h2(args, log)
  File "/home/genetics/Desktop/ptsd_analysis_10/ldsc/ldscore/sumstats.py", line 258, in estimate_h2
    args, log, args.h2)
  File "/home/genetics/Desktop/ptsd_analysis_10/ldsc/ldscore/sumstats.py", line 234, in _read_ld_sumstats
    sumstats = _read_sumstats(args, log, fh, alleles=alleles, dropna=dropna)
  File "/home/genetics/Desktop/ptsd_analysis_10/ldsc/ldscore/sumstats.py", line 165, in _read_sumstats
    sumstats = sumstats.drop_duplicates(subset='SNP')
TypeError: drop_duplicates() got an unexpected keyword argument 'subset'

Any advice?
Thanks

**Comment by bulik** [comment]
I think this means you're using an old version of `pandas`. From the command line, try `pip install --upgrade pandas` and see if that helps.

**Comment by adamxm** [comment]
It worked. Thank you very much
