### ISSUE TITLE
error

### ISSUE THREAD

**Issue by xiangboyulan** [bulik/ldsc#309]
Call: 
./ldsc.py \
--ref-ld-chr /home/huawei/xb/software/ldsc/eur_w_ld_chr \
--out test \
--rg A1.sumstats.gz,phylum.B1.sumstats.gz \
--w-ld-chr /home/huawei/xb/software/ldsc/eur_w_ld_chr 

Beginning analysis at Fri Sep 10 09:16:00 2021
Reading summary statistics from A1.sumstats.gz ...
Read summary statistics for 1064601 SNPs.
Reading reference panel LD Score from /home/huawei/xb/software/ldsc/eur_w_ld_chr[1-22] ... (ldscore_fromlist)
Traceback (most recent call last):
  File "/home/huawei/xb/software/ldsc/ldsc.py", line 642, in <module>
    sumstats.estimate_rg(args, log)
  File "/home/huawei/xb/software/ldsc/ldscore/sumstats.py", line 397, in estimate_rg
    alleles=True, dropna=True)
  File "/home/huawei/xb/software/ldsc/ldscore/sumstats.py", line 243, in _read_ld_sumstats
    ref_ld = _read_ref_ld(args, log)
  File "/home/huawei/xb/software/ldsc/ldscore/sumstats.py", line 82, in _read_ref_ld
    'reference panel LD Score', ps.ldscore_fromlist)
  File "/home/huawei/xb/software/ldsc/ldscore/sumstats.py", line 152, in _read_chr_split_files
    out = parsefunc(_splitp(chr_arg), _N_CHR, **kwargs)
  File "/home/huawei/xb/software/ldsc/ldscore/parse.py", line 103, in ldscore_fromlist
    y = ldscore(fh, num)
  File "/home/huawei/xb/software/ldsc/ldscore/parse.py", line 147, in ldscore
    first_fh = sub_chr(fh, chrs[0]) + suffix
IndexError: list index out of range

Analysis finished at Fri Sep 10 09:16:02 2021
Total time elapsed: 2.07s
Traceback (most recent call last):
  File "/home/huawei/xb/software/ldsc/ldsc.py", line 642, in <module>
    sumstats.estimate_rg(args, log)
  File "/home/huawei/xb/software/ldsc/ldscore/sumstats.py", line 397, in estimate_rg
    alleles=True, dropna=True)
  File "/home/huawei/xb/software/ldsc/ldscore/sumstats.py", line 243, in _read_ld_sumstats
    ref_ld = _read_ref_ld(args, log)
  File "/home/huawei/xb/software/ldsc/ldscore/sumstats.py", line 82, in _read_ref_ld
    'reference panel LD Score', ps.ldscore_fromlist)
  File "/home/huawei/xb/software/ldsc/ldscore/sumstats.py", line 152, in _read_chr_split_files
    out = parsefunc(_splitp(chr_arg), _N_CHR, **kwargs)
  File "/home/huawei/xb/software/ldsc/ldscore/parse.py", line 103, in ldscore_fromlist
    y = ldscore(fh, num)
  File "/home/huawei/xb/software/ldsc/ldscore/parse.py", line 147, in ldscore
    first_fh = sub_chr(fh, chrs[0]) + suffix
IndexError: list index out of range

**Comment by tshhhh** [comment]
Hello, I also encountered the same error. Have you solved it? How should I solve it?

**Comment by chunyu-yes** [comment]
The same error happened.

**Comment by tshhhh** [comment]
您好，
虽然我没有解决那个问题，但是我在知乎上看到有人直接在windows系统下做了，Windows系统下LDSC等软件的解决策略 - 知乎 (zhihu.com)
我想应该可以解决这个问题，但我没有试过
我用了另一种方法代替了LDSC，叫Sumher
希望对您有帮助


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bulik/ldsc"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月2日(星期二) 晚上7:49
***@***.***&gt;;
抄送:&nbsp;" ***@***.******@***.***&gt;;
主题:&nbsp;Re: [bulik/ldsc] error (#309)





 
The same error happened.
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by CaoLuYao98** [comment]
Same as you. Have anyone solved the error? Please help us.

**Comment by YaoXueming** [comment]
Hello,guys, I met the same problem when conducted cell type annlysis. And here is my solution.Please check you command is right and make sure your weights files, baseline files, the directory contain the cell-type specific ld scores, and ldcts file for cell type in **same** directory. 
And when you conduct cell type or other heritability enrichment analysis, you should enter into the directory containing all input files and then run the software.

here is a example of my comamnd:
(ldsc) xiaohong@DNA:~/database/ldsc_ref$ /f/xiaohonglab/xiaohong/software/ldsc-master/ldsc.py --h2-cts /f/xiaohonglab/xiaohong/database/ldsc_ref/multiomics/metal_neff_cell.sumstats.gz --ref-ld-chr /f/xiaohonglab/xiaohong/database/ldsc_ref/1000G_EUR_Phase3_baseline/baseline. --out /f/xiaohonglab/xiaohong/database/ldsc_ref/multiomics/metal_neff_scATAC  --w-ld-chr /f/xiaohonglab/xiaohong/database/ldsc_ref/weights_hm3_no_hla/weights. --ref-ld-chr-cts /f/xiaohonglab/xiaohong/database/ldsc_ref/multiomics.ldcts

I hope it will help you!

**Comment by tshhhh** [comment]
Hello,&nbsp;
Have you done genetic correlation? 'eur_w_ld_Chr' is a folder containing many files. I combine this folder with the data to be analyzed and ldsc .Py is placed in a directory, but an error is reported. Can you explain how to put the data in a directory?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bulik/ldsc"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月1日(星期五) 下午4:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bulik/ldsc] error (#309)





 
Hello,guys, I met the same problem when conduted cell type annlysis. And here is my solution.Please check you comand is right and make sure your weights files, baseline files, the dirctory contain the cell-type specific ld scores, and ldcts file for cell type in same directory.
 And when you conduct cell type or other heritability enrichment analysis, you should enter into the dirctory containing all input files and then run the software.
 
here is a example of my comamnd:
 (ldsc) ***@***.***:~/database/ldsc_ref$ /f/xiaohonglab/xiaohong/software/ldsc-master/ldsc.py --h2-cts /f/xiaohonglab/xiaohong/database/ldsc_ref/multiomics/metal_neff_cell.sumstats.gz --ref-ld-chr /f/xiaohonglab/xiaohong/database/ldsc_ref/1000G_EUR_Phase3_baseline/baseline. --out /f/xiaohonglab/xiaohong/database/ldsc_ref/multiomics/metal_neff_scATAC  --w-ld-chr /f/xiaohonglab/xiaohong/database/ldsc_ref/weights_hm3_no_hla/weights. --ref-ld-chr-cts /f/xiaohonglab/xiaohong/database/ldsc_ref/multiomics.ldcts
 
I hope it will help you!

**Comment by anja-ch** [comment]
Hi I've just got the same error but I don't understand the solution. I think I have done something similar as what you say @YaoXueming . Would you be able to explain a bit more what you changed from what was posted in the original? 

I am trying to do a simple snp heritability calculation using --h2:
python2 ldsc.py --h2 ../../hm3_pheno.sumstats.gz --ref-ld-chr eur_w_ld_chr/ --w-ld-chr eur_w_ld_chr/ --out ../../pheno_h2

But I get exactly the same error as @xiangboyulan got..

**Comment by littlehegemon** [comment]
I have the same problem and finally solved. You only need to make sure that you have enter the FULL prefix before chromosome number. 

....../weights. -- NOT WORKING

....../weights.hm3_noMHC. -- WORKS

**Comment by yangchuhua** [comment]
If you download SNPs and reference from https://ibg.colorado.edu/cdrom2021/Day06-nivard/GenomicSEM_practical/eur_w_ld_chr/, and use them, this will be solved.

**Comment by Tumai93** [comment]
> Hi I've just got the same error but I don't understand the solution. I think I have done something similar as what you say [@YaoXueming](https://github.com/YaoXueming) . Would you be able to explain a bit more what you changed from what was posted in the original?
> 
> I am trying to do a simple snp heritability calculation using --h2: python2 ldsc.py --h2 ../../hm3_pheno.sumstats.gz --ref-ld-chr eur_w_ld_chr/ --w-ld-chr eur_w_ld_chr/ --out ../../pheno_h2
> 
> But I get exactly the same error as [@xiangboyulan](https://github.com/xiangboyulan) got..

did you ever find the solution?

**Comment by anja-ch** [comment]
> > Hi I've just got the same error but I don't understand the solution. I think I have done something similar as what you say [@YaoXueming](https://github.com/YaoXueming) . Would you be able to explain a bit more what you changed from what was posted in the original?
> > I am trying to do a simple snp heritability calculation using --h2: python2 ldsc.py --h2 ../../hm3_pheno.sumstats.gz --ref-ld-chr eur_w_ld_chr/ --w-ld-chr eur_w_ld_chr/ --out ../../pheno_h2
> > But I get exactly the same error as [@xiangboyulan](https://github.com/xiangboyulan) got..
> 
> did you ever find the solution?

I did find the solution but if I'm honest i can't remember what the specific issue was now. I know I had two issues in the past: setting up ldsc in the right way and making sure that my data was in a format that worked with ldsc. 
For setting up ldsc correctly - 
I use python2.7 https://www.python.org/downloads/release/python-2718/ because the packages required for this analysis run on this version of python. I use a virtual environment (made using 'python2 -m virtualenv myenv') and then I make sure it has all of the necessary packages installed.
For issues with data - 
It's important to make sure that the summary statistics you're using don't have any data that ldsc cant read - at one point I know I was having some issues because there was string data in my numerical columns. I check this by reading it into R and looking at the data type that R has interpreted the numerical columns as. If the beta, freq, p-values etc. are not being read as numerical data then there may be a problem in the data

Hope that helps!
