### ISSUE TITLE
error for generate ldscore file when no annotation in that chromosome

### ISSUE THREAD

**Issue by zzz2010** [bulik/ldsc#34]
Hi, 
       I found when the annot file is a complete 0 matrix, the script can not generate the ldscore file.
Anyway to fix that?

The log is below:
Call:
./ldsc.py \
--print-snps LDSCORE/hm.22.snp \
--ld-wind-cm 1.0 \
--out /home/unix/zzhang/hptmp/LDscoreTmp/igap_pval5.rsid.22 \
--bfile LDSCORE/1000G.mac5eur.22 \
--annot /broad/hptmp/zhizhuo/LDscoreAnnot/igap_pval5.rsid.22.annot.gz \
--l2

Beginning analysis at Thu Jun 11 11:17:35 2015
Read list of 129364 SNPs from LDSCORE/1000G.mac5eur.22.bim
Read 53 annotations for 129364 SNPs from /broad/hptmp/zhizhuo/LDscoreAnnot/igap_pval5.rsid.22.annot.gz
Read list of 379 individuals from LDSCORE/1000G.mac5eur.22.fam
Reading genotypes from LDSCORE/1000G.mac5eur.22.bed
After filtering, 129364 SNPs remain
Estimating LD Score.
Traceback (most recent call last):
  File "ldsc-master/ldsc.py", line 606, in <module>
    ldscore(args, log)
  File "ldsc-master/ldsc.py", line 318, in ldscore
    df.columns = new_colnames
  File "/broad/software/free/Linux/redhat_6_x86_64/pkgs/anaconda_2.1.0/lib/python2.7/site-packages/pandas/core/generic.py", line 1958, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/src/properties.pyx", line 65, in pandas.lib.AxisProperty.__set__ (pandas/lib.c:41294)
  File "/broad/software/free/Linux/redhat_6_x86_64/pkgs/anaconda_2.1.0/lib/python2.7/site-packages/pandas/core/generic.py", line 406, in _set_axis
    self._data.set_axis(axis, labels)
  File "/broad/software/free/Linux/redhat_6_x86_64/pkgs/anaconda_2.1.0/lib/python2.7/site-packages/pandas/core/internals.py", line 2217, in set_axis
    'new values have %d elements' % (old_len, new_len))
ValueError: Length mismatch: Expected axis has 6 elements, new values have 58 elements

**Comment by bulik** [comment]
Why do you want to pass ldsc an annot matrix that is all zeros? Then the LD Scores will be all zeros?

Or is this an annotation that is zero on chr 22 but nonzero elsewhere?

**Comment by zzz2010** [comment]
Yes, the annotation that is zero on chr22 but nonzero in other chromosomes.

Also, I tried to create the all zeros ldscore file and the M_5_50 file manually. But they will cause error in the later heritability partition task.

**Comment by bulik** [comment]
ok, I'll look into it.

In the meantime, you can work around this by concatenating your 22 LD Score files into a single file (NB: remove all the first header) and making a new M_5_50 file which is the sum of the per-chromosome M_5_50 files.

**Comment by Lassana1** [comment]
Hi zzz2010,
                Could you be so kind enough to share the format of your annot files that worked to generate ld score files? I get errors with all my annotation files.

Thanks
