### ISSUE TITLE
FloatingPointError: invalid value encountered in divide

### ISSUE THREAD

**Issue by meghatron21** [bulik/ldsc#345]
Hi. I'm trying to use LDSC to get heritability estimates for non-European populations. I'm running the following command:

python ~/Programs/ldsc/ldsc.py --h2 $folder.$pheno.sumstats.gz --ref-ld-chr $ref_dir --w-ld-chr $weights_dir --out $folder.$pheno.herit

But I'm getting the following error:

Traceback (most recent call last):
  File "/cellar/users/mpagadal/Programs/ldsc/ldsc.py", line 644, in <module>
    sumstats.estimate_h2(args, log)
  File "/cellar/users/mpagadal/Programs/ldsc/ldscore/sumstats.py", line 359, in estimate_h2
    twostep=args.two_step, old_weights=old_weights)
  File "/cellar/users/mpagadal/Programs/ldsc/ldscore/regressions.py", line 346, in __init__
    slow=slow, step1_ii=step1_ii, old_weights=old_weights)
  File "/cellar/users/mpagadal/Programs/ldsc/ldscore/regressions.py", line 224, in __init__
    M, M_tot, self.cat, self.tot)
  File "/cellar/users/mpagadal/Programs/ldsc/ldscore/regressions.py", line 301, in _enrichment
    enrichment = np.divide(cat, M) / (tot / M_tot)
FloatingPointError: invalid value encountered in divide

I have run this same command before with no issues, so not quite sure what is going on and it is working fine for my European population.

Thanks,
Meghana

**Comment by maxwellreynolds** [comment]
Did you ever resolve this issue? I am having the same error

**Comment by mygonia** [comment]
I'm having the same problem. I'll update you if I find a fix.

**Comment by JinRenelf** [comment]
I'm having the same issue? Does anyone know how to fix it?
