### ISSUE TITLE
Cell type specific analyses index error

### ISSUE THREAD

**Issue by afcmalone** [bulik/ldsc#349]
Hi,
I am getting an error running cell type specific regressions as described in https://github.com/bulik/ldsc/wiki/Cell-type-specific-analyses but using my own data.
I get: 'IndexError: list index out of range'

Thank you in advance!

Here is my code and log:
Call: 
./ldsc.py \
--h2-cts CKDGEN_UACR.sumstats.gz \
--ref-ld-chr 1000G_EUR_Phase3_baseline/baseline. \
--out BMI_FSGS \
--ref-ld-chr-cts fsgs.ldcts \
--w-ld-chr weights_hm3_no_hla/ 

Beginning analysis at Thu Jun 30 09:34:02 2022
Reading summary statistics from CKDGEN_UACR.sumstats.gz ...
Read summary statistics for 525171 SNPs.
Reading reference panel LD Score from 1000G_EUR_Phase3_baseline/baseline.[1-22] ... (ldscore_fromlist)
Read reference panel LD Scores for 1190321 SNPs.
Removing partitioned LD Scores with zero variance.
Reading regression weight LD Score from weights_hm3_no_hla/[1-22] ... (ldscore_fromlist)
Traceback (most recent call last):
  File "ldsc.py", line 646, in <module>
    sumstats.cell_type_specific(args, log)
  File "/home/malone/Andrew/ldsc/ldscore/sumstats.py", line 263, in cell_type_specific
    _read_ld_sumstats(args, log, args.h2_cts)
  File "/home/malone/Andrew/ldsc/ldscore/sumstats.py", line 247, in _read_ld_sumstats
    w_ld = _read_w_ld(args, log)
  File "/home/malone/Andrew/ldsc/ldscore/sumstats.py", line 134, in _read_w_ld
    'regression weight LD Score', ps.ldscore_fromlist)
  File "/home/malone/Andrew/ldsc/ldscore/sumstats.py", line 152, in _read_chr_split_files
    out = parsefunc(_splitp(chr_arg), _N_CHR, **kwargs)
  File "/home/malone/Andrew/ldsc/ldscore/parse.py", line 103, in ldscore_fromlist
    y = ldscore(fh, num)
  File "/home/malone/Andrew/ldsc/ldscore/parse.py", line 147, in ldscore
    first_fh = sub_chr(fh, chrs[0]) + suffix
IndexError: list index out of range

Analysis finished at Thu Jun 30 09:34:20 2022
Total time elapsed: 17.45s

**Comment by LiJie1421128585** [comment]
Have you solved the problem ?

**Comment by LiJie1421128585** [comment]
Have you solved the problem ?

**Comment by cwnag-c** [comment]
Have you solved the problem ?

**Comment by ruimin-1212** [comment]
Have you solve the problem?

**Comment by elfthrith** [comment]
Has anyone resolved this issue? It's been a puzzle for me.

**Comment by jxcao98** [comment]
Have you solve the problem?

**Comment by jxcao98** [comment]
Oh, I think I’ve figured out the issue. The `*.ldcts` file uses relative paths to locate the annotation files, so we either need to run `ldsc `from the same directory where `*.ldcts` is located, or manually update the `*.ldcts` file to use absolute paths instead.

**Comment by aksarkar** [comment]
The error

```
first_fh = sub_chr(fh, chrs[0]) + suffix
IndexError: list index out of range
```

usually indicates that there is an error in the command line arguments, leading to no files found matching the file name pattern given.

**Comment by complexgenome** [comment]
@aksarkar Hi, the files are present. I run as the tutorial asks us.

@jxcao98 - Can you please explain in a bit more detail?

I'm trying to run as:

```
/sc/arion/projects/gapslab/team_folders/sanjeev/conda_envs/.conda/envs/ldsc/bin/python /sc/arion/projects/gapslab/team_folders/sanjeev/ldsc/ldsc.py --h2-cts /sc/arion/projects/gapslab/projects/imaging_AD_dep_correlation/ldsc_heritability/depression_ldsc.sumstats.gz --ref-ld-chr 1000G_EUR_Phase3_baseline/baselineLD. --out mdd_Multi_tissue_gene_expr --ref-ld-chr-cts ./Multi_tissue_gene_expr.ldcts --w-ld-chr weights_hm3_no_hla/weights.
```

the Multi_tissue_gene_expr.ldcts is present in the directory where I am running this. Still I get the index out of error.

**Comment by jxcao98** [comment]
@complexgenome This seems unusual. Based on my experience, you need to make sure the path to the `Multi_tissue_gene_expr.ldcts` file is directly accessible, and keep in mind that it's a relative path.
