### ISSUE TITLE
TypeError: can only concatenate list (not "dict_keys") to list

### ISSUE THREAD

**Issue by MenglinC** [bulik/ldsc#354]
ls there Anybody can help me ? I am stuck in here!

```
(base) [xxzhang@mu02 ldsc_test]$ python3 /home/xxzhang/workplace/software/ldsc-master/mu                                                      nge_sumstats_v3.py --sumstats GIANT_BMI_Speliotes2010_publicrelease_HapMapCeuFreq.txt --                                                      merge-alleles w_hm3.snplist  --out BMI --a1-inc
*********************************************************************
* LD Score Regression (LDSC)
* Version 1.0.1
* (C) 2014-2019 Brendan Bulik-Sullivan and Hilary Finucane
* Broad Institute of MIT and Harvard / MIT Department of Mathematics
* GNU General Public License v3
*********************************************************************
Call:
./munge_sumstats.py \
--sumstats GIANT_BMI_Speliotes2010_publicrelease_HapMapCeuFreq.txt \
--out BMI \
--merge-alleles w_hm3.snplist \
--a1-inc


ERROR converting summary statistics:


Conversion finished at Sun Oct  2 19:24:45 2022
Total time elapsed: 0.0s
Traceback (most recent call last):
  File "/home/xxzhang/workplace/software/ldsc-master/munge_sumstats_v3.py", line 566, in                                                       munge_sumstats
    flag_cnames, mod_default_cnames, ignore_cnames)
  File "/home/xxzhang/workplace/software/ldsc-master/munge_sumstats_v3.py", line 147, in                                                       get_cname_map
    {x: default[x] for x in default if x not in clean_ignore + flag.keys()})
  File "/home/xxzhang/workplace/software/ldsc-master/munge_sumstats_v3.py", line 147, in                                                       <dictcomp>
    {x: default[x] for x in default if x not in clean_ignore + flag.keys()})
TypeError: can only concatenate list (not "dict_keys") to list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xxzhang/workplace/software/ldsc-master/munge_sumstats_v3.py", line 741, in                                                       <module>
    munge_sumstats(parser.parse_args(), p=True)
  File "/home/xxzhang/workplace/software/ldsc-master/munge_sumstats_v3.py", line 733, in                                                       munge_sumstats
    log.log(traceback.format_exc(ex))
  File "/home/xxzhang/miniconda3/lib/python3.6/traceback.py", line 167, in format_exc
    return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))
  File "/home/xxzhang/miniconda3/lib/python3.6/traceback.py", line 121, in format_except                                                      ion
    type(value), value, tb, limit=limit).format(chain=chain))
  File "/home/xxzhang/miniconda3/lib/python3.6/traceback.py", line 509, in __init__
    capture_locals=capture_locals)
  File "/home/xxzhang/miniconda3/lib/python3.6/traceback.py", line 338, in extract
    if limit >= 0:
TypeError: '>=' not supported between instances of 'TypeError' and 'int'

```

**Comment by MenglinC** [comment]
and I fix it by  adding the list() in the line 147:
```python
	clean_ignore = [clean_header(x) for x in ignore]
	cname_map = {x: flag[x] for x in flag if x not in clean_ignore}
	cname_map.update(
		{x: default[x] for x in default if x not in clean_ignore + list(flag.keys())}) #this
	return cname_map
```
**reference：** https://github.com/bulik/ldsc/issues/159
