### ISSUE TITLE
UnboundLocalError: local variable 'cname_translation' referenced before assignment

### ISSUE THREAD

**Issue by MenglinC** [bulik/ldsc#355]
```python
(base) [xxzhang@mu02 ldsc_test]$ python3 /home/xxzhang/workplace/software/ldsc-master/munge_sumstats_v3.py --sumstats GIANT_BMI_Speliotes2010_publicrelease_HapMapCeuFreq.txt --merge-alleles w_hm3.snplist  --out BMI --a1-inc
*********************************************************************
* LD Score Regression (LDSC)
* Version 1.0.1
* (C) 2014-2019 Brendan Bulik-Sullivan and Hilary Finucane
* Broad Institute of MIT and Harvard / MIT Department of Mathematics
* GNU General Public License v3
*********************************************************************
Call:
./munge_sumstats.py \
--sumstats GIANT_BMI_Speliotes2010_publicrelease_HapMapCeuFreq.txt \
--out BMI \
--merge-alleles w_hm3.snplist \
--a1-inc


ERROR converting summary statistics:


Conversion finished at Sun Oct  2 20:12:34 2022
Total time elapsed: 0.0s
Traceback (most recent call last):
  File "/home/xxzhang/workplace/software/ldsc-master/munge_sumstats_v3.py", line 626, in munge_sumstats
    for field in cname_translation:
UnboundLocalError: local variable 'cname_translation' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xxzhang/workplace/software/ldsc-master/munge_sumstats_v3.py", line 740, in <module>
    munge_sumstats(parser.parse_args(), p=True)
  File "/home/xxzhang/workplace/software/ldsc-master/munge_sumstats_v3.py", line 732, in munge_sumstats
    log.log(traceback.format_exc(ex))
  File "/home/xxzhang/miniconda3/lib/python3.6/traceback.py", line 167, in format_exc
    return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))
  File "/home/xxzhang/miniconda3/lib/python3.6/traceback.py", line 121, in format_exception
    type(value), value, tb, limit=limit).format(chain=chain))
  File "/home/xxzhang/miniconda3/lib/python3.6/traceback.py", line 509, in __init__
    capture_locals=capture_locals)
  File "/home/xxzhang/miniconda3/lib/python3.6/traceback.py", line 338, in extract
    if limit >= 0:
TypeError: '>=' not supported between instances of 'UnboundLocalError' and 'int'
```

**Comment by MenglinC** [comment]
python treasures the indent ,so please check the logic in the code context.
