### ISSUE TITLE
Error converting summary statistics

### ISSUE THREAD

**Issue by simona0mind** [bulik/ldsc#356]
Hello, I need help for troubleshooting. Run "munge.py", get "errors". Not sure what was wrong...
The log is attached below. 
Thank you!

[mungeinsom.log](https://github.com/bulik/ldsc/files/9711917/mungeinsom.log)
all: 
./munge_sumstats.py \
--out mungeinsom \
--merge-alleles w_hm3.snplist \
--frq frequency \
--N-col N \
--a1 A1 \
--a2 A2 \
--snp SNP \
--sumstats testuk43insom.txt.gz \
--p P 

Interpreting column names as follows:
N:	Sample size
A1:	Allele 1, interpreted as ref allele for signed sumstat.
A2:	Allele 2, interpreted as non-ref allele for signed sumstat.
frequency:	Allele frequency
SNP:	Variant ID (e.g., rs number)
Z:	Z-score (0 --> no effect; above 0 --> A1 is trait/risk increasing)
pvalue:	p-Value

Reading list of SNPs for allele merge from w_hm3.snplist
Read 1217311 SNPs for allele merge.
Reading sumstats from testuk43insom.txt.gz into memory 5000000 SNPs at a time.
Read 8856162 SNPs from --sumstats file.
Removed 7427968 SNPs not in --merge-alleles.
Removed 251724 SNPs with missing values.
Removed 0 SNPs with INFO <= 0.9.
Removed 0 SNPs with MAF <= 0.01.
Removed 0 SNPs with out-of-bounds p-values.
Removed 1 variants that were not SNPs or were strand-ambiguous.
1176469 SNPs remain.
Removed 2 SNPs with duplicated rs numbers (1176467 SNPs remain).
Removed 0 SNPs with N < 224643.333333 (1176467 SNPs remain).
Median value of Z was 0.000237678192207, which seems sensible.
Removed 42 SNPs whose alleles did not match --merge-alleles (1176425 SNPs remain).

ERROR converting summary statistics:

Traceback (most recent call last):
  File "ldsc/munge_sumstats.py", line 707, in munge_sumstats
    dat = allele_merge(dat, merge_alleles, log)
  File "ldsc/munge_sumstats.py", line 445, in allele_merge
    dat.loc[~jj, [i for i in dat.columns if i != 'SNP']] = float('nan')
  File "/opt/anaconda3/envs/ldsc/lib/python2.7/site-packages/pandas/core/indexing.py", line 189, in __setitem__
    indexer = self._get_setitem_indexer(key)
  File "/opt/anaconda3/envs/ldsc/lib/python2.7/site-packages/pandas/core/indexing.py", line 167, in _get_setitem_indexer
    return self._convert_tuple(key, is_setter=True)
  File "/opt/anaconda3/envs/ldsc/lib/python2.7/site-packages/pandas/core/indexing.py", line 248, in _convert_tuple
    idx = self._convert_to_indexer(k, axis=i, is_setter=is_setter)
  File "/opt/anaconda3/envs/ldsc/lib/python2.7/site-packages/pandas/core/indexing.py", line 1354, in _convert_to_indexer
    return self._get_listlike_indexer(obj, axis, **kwargs)[1]
  File "/opt/anaconda3/envs/ldsc/lib/python2.7/site-packages/pandas/core/indexing.py", line 1161, in _get_listlike_indexer
    raise_missing=raise_missing)
  File "/opt/anaconda3/envs/ldsc/lib/python2.7/site-packages/pandas/core/indexing.py", line 1246, in _validate_read_indexer
    key=key, axis=self.obj._get_axis_name(axis)))
KeyError: u"None of [Int64Index([-2, -2, -2, -2, -2, -1, -2, -2, -2, -1,\n            ...\n            -1, -2, -2, -2, -1, -1, -2, -2, -2, -2], dtype='int64', length=1217311)] are in the [index]"

**Comment by complexgenome** [comment]
Hello there
Were you able to resolve this?
