### ISSUE TITLE
Getting module parse has no attibute error

### ISSUE THREAD

**Issue by akhilpampana** [bulik/ldsc#369]
Hello, 

I am trying to calcualate heritbaility and I am getting this issue. May I know how to resolve this?

Code:
python3 dsc.py --h2 sbp_hapmap.sumstats.gz  --ref-ld-chr eur_w_ld_chr/  --w-ld-chr eur_w_ld_chr/ --out sbp_h2_eur

Error:
Analysis finished at Fri Feb 24 12:40:08 2023
Total time elapsed: 0.0s
Traceback (most recent call last):
  File "ldsc.py", line 683, in <module>
    sumstats.estimate_h2(args, log)
  File "ldscore/sumstats.py", line 326, in estimate_h2
    M_annot, w_ld_cname, ref_ld_cnames, sumstats, novar_cols = _read_ld_sumstats(args, log, args.h2)
  File "ldscore/sumstats.py", line 243, in _read_ld_sumstats
    sumstats = _read_sumstats(args, log, fh, alleles=alleles, dropna=dropna)
  File "ldscore/sumstats.py", line 164, in _read_sumstats
    sumstats = ps.sumstats(fh, alleles=alleles, dropna=dropna)
AttributeError: module 'parse' has no attribute 'sumstats'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ldsc.py", line 694, in <module>
    log.log( traceback.format_exc(ex) )
  File "/share/apps/rc/software/Anaconda3/2022.05/lib/python3.9/traceback.py", line 167, in format_exc
    return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))
  File "/share/apps/rc/software/Anaconda3/2022.05/lib/python3.9/traceback.py", line 120, in format_exception
    return list(TracebackException(
  File "/share/apps/rc/software/Anaconda3/2022.05/lib/python3.9/traceback.py", line 517, in __init__
    self.stack = StackSummary.extract(
  File "/share/apps/rc/software/Anaconda3/2022.05/lib/python3.9/traceback.py", line 340, in extract
    if limit >= 0:
TypeError: '>=' not supported between instances of 'AttributeError' and 'int'

I will be waiting for your response. 

Regards
Akhil

**Comment by CandyLucky** [comment]
I have the same problem, have you solved it?

**Comment by akhilpampana** [comment]
I have performed these steps and resolved each step/error independently after that. 

> - Load anaconda2 and run the analysis
> - Convert everything to python2 and check for indentations
> - Remove print function in ldsc - Removed it as its printing null error as its printing dimension of the matrix.
> - Keep paths for reference 
> - Install all packages required to run in Python –user 
> - pip3 install parse –user 
> - pip3 install regressions –user
> - pip3 install bitarray –user
> - pip3 install jackknife –user
> - pip3 install bitarray --user

**Comment by CandyLucky** [comment]
Thank you for your reply. I have installed all packages, and ldsc.py -h can print a list of all command-line options. However, when running ”python3 ldsc.py --h2 50_irnt.gwas.imputed_v3.both_sexes.tsv.bgz --w-ld-chr SNP. --overlap-annot --ref-ld-chr SNP --frqfile-chr SNP --out out“ , an error AttributeError: module 'parse' has no attribute 'sumstats' will appear; and when I run the ldsc.py command alone, it shows ModuleNotFoundError: No module named 'ldscore'. Does this mean that my ldsc installation actually failed?

**Comment by akhilpampana** [comment]
No, you should have an LD score folder, meaning the installation works as far as I understand.

In the ldsc.py code, do something like this 

> from __future__ import division
> import sys
> import ldscore.ldscore as ld
> import ldscore.parse as ps
> import ldscore.sumstats as sumstats
> import ldscore.regressions as reg
> import numpy as np
> import pandas as pd
> from subprocess import call
> from itertools import product
> import time
> import sys
> import traceback
> import argparse
> from functools import reduce


at the import part of the code in ldsc.py.

**Comment by RXMa-Bio-software** [comment]
Thank you very much for your reply. My ldsc.py contains 
from __future__ import division
import ldscore.ldscore as ld
import ldscore.parse as ps
import ldscore.sumstats as sumstats
import ldscore.regressions as reg
import numpy as np
import pandas as pd
from subprocess import call
from itertools import product
import time, sys, traceback, argparse

But it keeps showing
Analysis finished at Mon Dec  2 11:53:25 2024
Total time elapsed: 0.0s
Traceback (most recent call last):
  File "/user/Tools/ldsc/ldsc.py", line 646, in <module>
    sumstats.estimate_h2(args, log)
  File "/user/Tools/ldsc/ldscore/sumstats.py", line 326, in estimate_h2
    args, log, args.h2)
  File "/user/Tools/ldsc/ldscore/sumstats.py", line 242, in _read_ld_sumstats
    sumstats = _read_sumstats(args, log, fh, alleles=alleles, dropna=dropna)
  File "/user/Tools/ldsc/ldscore/sumstats.py", line 163, in _read_sumstats
    sumstats = ps.sumstats(fh, alleles=alleles, dropna=dropna)
AttributeError: module 'parse' has no attribute 'sumstats'

So, I'm not sure where the problem lies

**Comment by CandyLucky** [comment]
Thank you very much for your reply. My ldsc.py contains 
from __future__ import division
import ldscore.ldscore as ld
import ldscore.parse as ps
import ldscore.sumstats as sumstats
import ldscore.regressions as reg
import numpy as np
import pandas as pd
from subprocess import call
from itertools import product
import time, sys, traceback, argparse

But it keeps showing
Analysis finished at Mon Dec  2 11:53:25 2024
Total time elapsed: 0.0s
Traceback (most recent call last):
  File "/user/Tools/ldsc/ldsc.py", line 646, in <module>
    sumstats.estimate_h2(args, log)
  File "/user/Tools/ldsc/ldscore/sumstats.py", line 326, in estimate_h2
    args, log, args.h2)
  File "/user/Tools/ldsc/ldscore/sumstats.py", line 242, in _read_ld_sumstats
    sumstats = _read_sumstats(args, log, fh, alleles=alleles, dropna=dropna)
  File "/user/Tools/ldsc/ldscore/sumstats.py", line 163, in _read_sumstats
    sumstats = ps.sumstats(fh, alleles=alleles, dropna=dropna)
AttributeError: module 'parse' has no attribute 'sumstats'

So, I'm not sure where the problem lies

**Comment by akhilpampana** [comment]
Hello, add import parse from ldscore. The parse for each of the helper scripts is linked to the main script of ldsc.py. The scripts below need to be updated.

![image](https://github.com/user-attachments/assets/61f96d9f-5f10-4ff7-8e30-d1e65cc405df)

**Comment by CandyLucky** [comment]
Thank you very much for your reply. 
I added “from ldscore import parse” in ldsc.py and updated the script below to the py3 version, but I still get the same error.

**Comment by akhilpampana** [comment]
Did you tried adding this into parse.py and try? import ldscore.sumstats as
sumstats

**Comment by CandyLucky** [comment]
Yes， I add “import ldscore.sumstats as sumstats”，but still getting an error


python user/Tools/ldsc/ldsc.py --h2 50_irnt.gwas.imputed_v3.both_sexes.tsv.bgz  --w-ld-chr SNP.1000Test --overlap-annot --ref-ld-chr SNP.1000Test --frqfile-chr SNP.1000Test --out BMI_baseline
*********************************************************************
* LD Score Regression (LDSC)
* Version 1.0.1
* (C) 2014-2019 Brendan Bulik-Sullivan and Hilary Finucane
* Broad Institute of MIT and Harvard / MIT Department of Mathematics
* GNU General Public License v3
*********************************************************************
Call:
./ldsc.py \
--out BMI_baseline \
--h2 50_irnt.gwas.imputed_v3.both_sexes.tsv.bgz \
--ref-ld-chr SNP.1000Test \
--w-ld-chr SNP.1000Test \
--overlap-annot  \
--frqfile-chr SNP.1000Test

Beginning analysis at Mon Dec  2 15:37:51 2024
Reading summary statistics from 50_irnt.gwas.imputed_v3.both_sexes.tsv.bgz ...
Traceback (most recent call last):
  File "user/Tools/ldsc/ldsc.py", line 651, in <module>
    sumstats.estimate_h2(args, log)
  File "user/Tools/ldsc/ldscore/sumstats.py", line 326, in estimate_h2
    args, log, args.h2)
  File "user/Tools/ldsc/ldscore/sumstats.py", line 242, in _read_ld_sumstats
    sumstats = _read_sumstats(args, log, fh, alleles=alleles, dropna=dropna)
  File "user/Tools/ldsc/ldscore/sumstats.py", line 163, in _read_sumstats
    sumstats = ps.sumstats(fh, alleles=alleles, dropna=dropna)
AttributeError: module 'parse' has no attribute 'sumstats'

Analysis finished at Mon Dec  2 15:37:51 2024
Total time elapsed: 0.0s
Traceback (most recent call last):
  File "user/Tools/ldsc/ldsc.py", line 651, in <module>
    sumstats.estimate_h2(args, log)
  File "user/Tools/ldsc/ldscore/sumstats.py", line 326, in estimate_h2
    args, log, args.h2)
  File "user/Tools/ldsc/ldscore/sumstats.py", line 242, in _read_ld_sumstats
    sumstats = _read_sumstats(args, log, fh, alleles=alleles, dropna=dropna)
  File "user/Tools/ldsc/ldscore/sumstats.py", line 163, in _read_sumstats
    sumstats = ps.sumstats(fh, alleles=alleles, dropna=dropna)
AttributeError: module 'parse' has no attribute 'sumstats'

**Comment by akhilpampana** [comment]
Can you add this to sumstat.py and try? import ldscore.parse as ps

**Comment by CandyLucky** [comment]
When I add ” import ldscore.parse as ps“ into  sumstat.py ，and getting an error
Traceback (most recent call last):
  File "/user/Tools/ldsc/ldsc.py", line 13, in <module>
    import ldscore.parse as ps
  File "/user/Tools/ldsc/ldscore/parse.py", line 14, in <module>
    import ldscore.sumstats as sumstats
  File "/user/Tools/ldsc/ldscore/sumstats.py", line 13, in <module>
    import ldscore.parse as ps
AttributeError: module 'ldscore' has no attribute 'parse'

**Comment by akhilpampana** [comment]
Remove ldscore. from the above and try?

**Comment by CandyLucky** [comment]
Thank you very much for your reply. A new error has occurred

Traceback (most recent call last):
  File "/user/Tools/ldsc/ldsc.py", line 15, in <module>
    import ldscore.sumstats as sumstats
  File "/user/Tools/ldsc/ldscore/sumstats.py", line 13, in <module>
    import ldscore.parse as ps
  File "/user/Tools/ldsc/ldscore/parse.py", line 14, in <module>
    import ldscore.sumstats as sumstats
AttributeError: module 'ldscore' has no attribute 'sumstats'


The modules called by each .py are as follows:

ldsc.py
from __future__ import division
import ldscore.ldscore as ld
import parse as ps
import ldscore.sumstats as sumstats
#import ldscore.regressions as reg
import regressions as reg
import numpy as np
import pandas as pd
from subprocess import call
from itertools import product
import time, sys, traceback, argparse
from functools import reduce

sumstats.py
from __future__ import division
import numpy as np
import pandas as pd
from scipy import stats
import itertools as it
import ldscore.parse as ps
import regressions as reg
import sys
import traceback
import copy
import os
import glob

parse.py
from __future__ import division
import numpy as np
import pandas as pd
import os
import glob
from ldscore import parse
import ldscore.sumstats as sumstats

regressuons.py 
from __future__ import division
import numpy as np
import pandas as pd
from scipy.stats import norm, chi2
import jackknife as jk
from ldscore import parse
import sys
sys.path.append("/user/Tools/ldsc/ldscore/")
from irwls import IRWLS
from scipy.stats import t as tdist
from collections import namedtuple

**Comment by akhilpampana** [comment]
Remove ldscore. for sumstats  in sumstats.py?

**Comment by akhilpampana** [comment]
I have played around a bunch resolving each step at a time. Knowing the
lines as in the error would help me understand clearly where the issue is.

**Comment by CandyLucky** [comment]
Thank you for your reply. Can you show me the format of ”sbp_hapmap.sumstats.gz“ file? I suspect there is something wrong with my input file.
Because when I used munge_sumstats.py to convert the format, I got an error message "/munge_sumstats.py", line 629, in munge_sumstats
raise ValueError('Could not find {C} column.'.format(C=c))
ValueError: Could not find SNP column.", so I used someone else's ready-made sumstats.gz file.

**Comment by akhilpampana** [comment]
Can you head your file and keep? Head your file, screenahot and attach
thereply.

**Comment by RXMa-Bio-software** [comment]
![AT N@ }QA23NQPMOPA{XY](https://github.com/user-attachments/assets/6c6cf493-e2c7-4864-80cb-7db6d74c1383)
This is my input file

**Comment by akhilpampana** [comment]
Your dataset should need to be in this format. https://github.com/bulik/ldsc/wiki/Summary-Statistics-File-Format

What's the issue u are getting when running munge_sumstats.py?

**Comment by RXMa-Bio-software** [comment]
Thank you for your reply. I'll try changing the format of the .sumstats file.
When I run munge_sumstats.py, having an error message "/munge_sumstats.py", line 629, in munge_sumstats
raise ValueError('Could not find {C} column.'.format(C=c))
ValueError: Could not find SNP column.", so I used someone else's ready-made sumstats.gz file. 
My input file 
![ZUR2`WOVNPG@(L25PBO{D6M](https://github.com/user-attachments/assets/ac7bedbf-7efa-4450-8238-7d387d353f45)
My coding: "python3 munge_sumstats.py --sumstats GIANT_BMI_Speliotes2010_publicrelease_HapMapCeuFreq.txt --merge-alleles w_hm3.snplist --out output --a1-inc --a1 Allele1 --a2 Allele2 --snp MArkerNAme"
Error: Conversion finished at Wed Dec  4 08:42:00 2024
Total time elapsed: 0.0s
Traceback (most recent call last):
  File "Tools/ldsc/munge_sumstats.py", line 630, in munge_sumstats
    raise ValueError('Could not find {C} column.'.format(C=c))
ValueError: Could not find SNP column.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Tools/ldsc/munge_sumstats.py", line 748, in <module>
    munge_sumstats(parser.parse_args(), p=True)
  File "Tools/ldsc/munge_sumstats.py", line 740, in munge_sumstats
    log.log(traceback.format_exc(ex))
  File "Tools/miniconda3/envs/ldsc_py3.6/lib/python3.6/traceback.py", line 167, in format_exc
    return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))
  File "Tools/miniconda3/envs/ldsc_py3.6/lib/python3.6/traceback.py", line 121, in format_exception
    type(value), value, tb, limit=limit).format(chain=chain))
  File "Tools/miniconda3/envs/ldsc_py3.6/lib/python3.6/traceback.py", line 509, in __init__
    capture_locals=capture_locals)
  File "Tools/miniconda3/envs/ldsc_py3.6/lib/python3.6/traceback.py", line 338, in extract
    if limit >= 0:
TypeError: '>=' not supported between instances of 'ValueError' and 'int'

The same error occurs when I replace the spaces in the input file with tabs

**Comment by akhilpampana** [comment]
Sumstata should have all the columns as mentioned in the link i shared and
also make sure these are linked to reference dataset. i.e rsids or
chrom:pos:ref:alt should match between reference file and ur file

**Comment by CandyLucky** [comment]
Thank you, but I am currently getting an error when converting the Sumstata format: "File "Tools/ldsc/munge_sumstats.py", line 630, in munge_sumstats
raise ValueError('Could not find {C} column.'.format(C=c))
ValueError: Could not find SNP column." 
My input file can match between reference file and ur file

**Comment by akhilpampana** [comment]
Can you send the head of the file? Name the columns as suggested in the
processing files in tutorial?

**Comment by RXMa-Bio-software** [comment]
Thank you, I ran it in the standard .sumstats format and got an error 
"import ldscore.sumstats as sumstats
AttributeError: module 'ldscore' has no attribute 'sumstats'"

**Comment by CandyLucky** [comment]
Thank you, I ran "Step 2: Partition heritability" by the standard .sumstats format and got an error
"import ldscore.sumstats as sumstats
AttributeError: module 'ldscore' has no attribute 'sumstats'"

**Comment by RXMa-Bio-software** [comment]
@@ZUR2`WOVNPG@(L25PBO{D6M
This is the information of converting .sumstats format

**Comment by RXMa-Bio-software** [comment]
This is the information of converting .sumstats format
![ZUR2`WOVNPG@(L25PBO{D6M](https://github.com/user-attachments/assets/579e2293-3f71-4bef-b9ab-6e86b5d8903d)

**Comment by akhilpampana** [comment]
Remove ldscore. and it should work.

**Comment by RXMa-Bio-software** [comment]
Thank you. When I delete xx and run the program, the error "File "/Tools/ldsc/ldsc.py", line 647, in <module>
sumstats.estimate_h2(args, log)
AttributeError: module 'sumstats' has no attribute 'estimate_h2'" will appear.

**Comment by CandyLucky** [comment]
Thank you very much. When I remove ldscore.  and run the program, the error "File "/Tools/ldsc/ldsc.py", line 647, in
sumstats.estimate_h2(args, log)
AttributeError: module 'sumstats' has no attribute 'estimate_h2'" will appear.

**Comment by akhilpampana** [comment]
try using this script and running? 
[ldsc.tar.gz](https://github.com/user-attachments/files/18016246/ldsc.tar.gz)

**Comment by CandyLucky** [comment]
Thank you very much. When I using your [ldsc.tar.gz](https://github.com/user-attachments/files/18016246/ldsc.tar.gz) file. and run the program, the error ”  File "/Tools/ldsc/ldsc.py", line 13, in <module>
    import ldscore.parse as ps
  File "/Tools/ldsc/ldscore/parse.py", line 14, in <module>
    import ldscore.sumstats as sumstats
  File "/Tools/ldsc/ldscore/sumstats.py", line 13, in <module>
    import ldscore.parse as ps
AttributeError: module 'ldscore' has no attribute 'parse'
“

**Comment by akhilpampana** [comment]
I think u have to move the scripts other than ldsc.py to ldscore folder to
run my code. I think thats the issue.

**Comment by RXMa-Bio-software** [comment]
Thank you very much. I reinstalled ldsc and used your file, and the following error occurred.
File "/Tools/ldsc/ldscore/parse.py", line 152, in ldscore
first_fh = sub_chr(fh, chrs[0]) + suffix
~~~~^^^
IndexError: list index out of range
During handling of the above exception, another exception occurred:

It may be caused by my input file. Can you help me check the format of the input file?
My command ” python3 ldsc.py  --h2 50_irnt.ldsc.1000.sumstats.gz --ref-ld-chr 50_irnt.ldsc.1000  --frqfile-chr 50_irnt.ldsc.1000.frq --w-ld-chr 50_irnt.ldsc.1000.weights3 --overlap-annot  --out 50_irnt.Test“ 
My input file
![Uploading FES3M7VHOJAAMXI5$MZ_P%F.png…]()

**Comment by CandyLucky** [comment]
Thank you very much. I reinstalled ldsc and used your file, and the following error occurred.

File "/Tools/ldsc/ldscore/parse.py", line 152, in ldscore
first_fh = sub_chr(fh, chrs[0]) + suffix
IndexError: list index out of range
During handling of the above exception, another exception occurred:

It may be caused by my input file. Can you help me check the format of the input file?
My command ” python3 ldsc.py  --h2 50_irnt.ldsc.1000.sumstats.gz --ref-ld-chr 50_irnt.ldsc.1000  --frqfile-chr 50_irnt.ldsc.1000.frq --w-ld-chr 50_irnt.ldsc.1000.weights3 --overlap-annot  --out 50_irnt.Test“ 
My input file
![Uploading FES3M7VHOJAAMXI5$MZ_P%F.png…]()

**Comment by RXMa-Bio-software** [comment]
![Uploading FES3M7VHOJAAMXI5$MZ_P%F.png…]()

**Comment by RXMa-Bio-software** [comment]
![Uploading FES3M7VHOJAAMXI5$MZ_P%F.png…]()

**Comment by akhilpampana** [comment]
Which build the dataset is in? Grch37 or 38? Also maybe check to see of
chromosome X is there is the dataset? Also I cannot able to see your input file

**Comment by akhilpampana** [comment]
Looks like code is not reading chromosomes correctly maybe the column name is wrong or formatting is wrong?

**Comment by CandyLucky** [comment]
Thank you very much for your kind help during this time, my problem has been solved, it was mainly caused by the fact that I have not been able to find the example file and my own file format was wrong. Thanks again and have a nice life.
