### ISSUE TITLE
Why do I keep reporting an error: Could not find SNP column？

### ISSUE THREAD

**Issue by ZyRose1** [bulik/ldsc#374]
(ldsc) python munge_sumstats.py \
> --sumstats /mnt/ndisk1/Student/zhouyi/GWAS_tools/TWAS/data/wellbeing_sum/WBresults.txt \
> --N 491455 \
> --signed-sumstats beta,0 \
> --snp snpid \
> --out SWB \
> --merge-alleles /mnt/ndisk1/Student/zhouyi/GWAS_tools/LDSC/baseline/baselinemodel/weights_hm3_no_hla
*********************************************************************
* LD Score Regression (LDSC)
* Version 1.0.1
* (C) 2014-2019 Brendan Bulik-Sullivan and Hilary Finucane
* Broad Institute of MIT and Harvard / MIT Department of Mathematics
* GNU General Public License v3
*********************************************************************
Call: 
./munge_sumstats.py \
--signed-sumstats beta,0 \
--out SWB \
--merge-alleles /mnt/ndisk1/Student/zhouyi/GWAS_tools/LDSC/baseline/baselinemodel/weights_hm3_no_hla \
--N 491455.0 \
--snp snpid \
--sumstats /mnt/ndisk1/Student/zhouyi/GWAS_tools/TWAS/data/wellbeing_sum/WBresults.txt 

ERROR converting summary statistics:

Traceback (most recent call last):
  File "munge_sumstats.py", line 627, in munge_sumstats
    raise ValueError('Could not find {C} column.'.format(C=c))
ValueError: Could not find SNP column.

Conversion finished at Fri Mar 24 11:30:21 2023
Total time elapsed: 0.0s
Traceback (most recent call last):
  File "munge_sumstats.py", line 745, in <module>
    munge_sumstats(parser.parse_args(), p=True)
  File "munge_sumstats.py", line 627, in munge_sumstats
    raise ValueError('Could not find {C} column.'.format(C=c))
ValueError: Could not find SNP column.

**Comment by minmin4003** [comment]
I have the same problem, have you solved it?

**Comment by zhowanu** [comment]
SNP ，not “SNP”，No double quotation marks

**Comment by 731104** [comment]
> I have the same problem, have you solved it?
have you solved the problem？

**Comment by 731104** [comment]
> SNP ，not “SNP”，No double quotation marks

I removed the double quotation marks, the error still existed. How to solve the problem? Many thanks.

**Comment by aksarkar** [comment]
@731104 You have specified `--snp snpid`. You need to ensure that the column header matches the argument.

**Comment by 731104** [comment]
> @731104 You have specified `--snp snpid`. You need to ensure that the column header matches the argument.
Many thanks again!

**Comment by xzt199610** [comment]
*********************************************************************
* LD Score Regression (LDSC)
* Version 1.0.1
* (C) 2014-2019 Brendan Bulik-Sullivan and Hilary Finucane
* Broad Institute of MIT and Harvard / MIT Department of Mathematics
* GNU General Public License v3
*********************************************************************
Call: 
./munge_sumstats.py \
--signed-sumstats beta,0 \
--out ./result/LPA \
--merge-alleles ./reference/w_hm3.snaplist \
--chunksize 500000 \
--a1 alt \
--a2 ref \
--snp rsid \
--sumstats ./sample/lpa.txt 


ERROR converting summary statistics:

Traceback (most recent call last):
  File "./munge_sumstats.py", line 627, in munge_sumstats
    raise ValueError('Could not find {C} column.'.format(C=c))
ValueError: Could not find SNP column.


Conversion finished at Tue Jul  9 12:48:40 2024
Total time elapsed: 0.01s
I also have met this problem even I have specified `--snp rsid`, What's the best way to fix this?

**Comment by aksarkar** [comment]
@xzt199610 It is not possible to answer your question without seeing the first line of the input file `./sample/lpa.txt`

**Comment by xzt199610** [comment]
@aksarkar This is several rows of my data. Many thanks. 

rsid,bp,ref,alt,se,beta,pval,N
rs1444281458,10485,G,A,0.0380333,-0.0296248,2.2E-01,174301
rs534229142,10511,G,A,0.0634967,-0.0156338,8.5E-01,174301
rs1387993806,10580,G,T,0.0512324,-0.0179897,9.7E-01,174301
rs1401057884,10705,A,G,0.0546404,0.0531506,2.2E-01,174301

**Comment by xzt199610** [comment]
And I have tried an example of [LDSC](https://cloufield.github.io/GWASTutorial/08_LDSC/#cross-trait-ld-score-regression). I found this demo file coded by unix. I tried to convert my data file into this style. But the same error appeared again. I hope you can solve this problem. It is grateful for your help.

**Comment by xzt199610** [comment]
And I have tried an example of [LDSC](https://cloufield.github.io/GWASTutorial/08_LDSC/#cross-trait-ld-score-regression). I found this demo file coded by unix. I tried to convert my data file into this style. But the same error appeared again. I hope you can solve this problem. It is grateful for your help. @aksarkar

**Comment by aksarkar** [comment]
@xzt199610 The file needs to be whitespace delimited, not comma-delimited. Replace the commas by tabs or single spaces.

**Comment by xzt199610** [comment]
@aksarkar Grateful for your help. I have solved the problem as you advised. Many thanks again.

**Comment by CandyLucky** [comment]
Hi, I also encountered the same problem. My input file is as follows. Errors will occur when using spaces and tabs as delimiters
GIANT.txt 
SNP A1 A2 BETA P N
rs10 A C 0.0333 0.708 80566
rs1000000 G A 0.6333 0.506 123865
rs10000010 C T 0.425 0.736 123827
rs10000012 C G 0.8083 0.042 123809
rs10000013 C A 0.1667 0.0689 123863
rs10000017 T C 0.2333 0.457 123262
rs1000002 C T 0.475 0.0322 123783
rs10000023 T G 0.5917 0.939 123756
rs10000029 T C 0.975 0.24 103623
rs1000003 G A 0.125 0.293 123743

w_hm3.snplist
SNP     A1      A2
rs10    A       C
rs1000000       G       A
rs10000010      C       T
rs10000012      C       G
rs10000013      C       A
rs10000017      T       C
rs1000002       C       T
rs10000023      T       G
rs10000029      T       C
rs1000003       G       A

Run Command
munge_sumstats.py --sumstats GIANT.txt  --merge-alleles w_hm3.snplist --snp SNP  --out test

I hope you can help me solve this problem，thanks

**Comment by 731104** [comment]
> Hi, I also encountered the same problem. My input file is as follows. Errors will occur when using spaces and tabs as delimiters GIANT.txt SNP A1 A2 BETA P N rs10 A C 0.0333 0.708 80566 rs1000000 G A 0.6333 0.506 123865 rs10000010 C T 0.425 0.736 123827 rs10000012 C G 0.8083 0.042 123809 rs10000013 C A 0.1667 0.0689 123863 rs10000017 T C 0.2333 0.457 123262 rs1000002 C T 0.475 0.0322 123783 rs10000023 T G 0.5917 0.939 123756 rs10000029 T C 0.975 0.24 103623 rs1000003 G A 0.125 0.293 123743
> 
> w_hm3.snplist SNP A1 A2 rs10 A C rs1000000 G A rs10000010 C T rs10000012 C G rs10000013 C A rs10000017 T C rs1000002 C T rs10000023 T G rs10000029 T C rs1000003 G A
> 
> Run Command munge_sumstats.py --sumstats GIANT.txt --merge-alleles w_hm3.snplist --snp SNP --out test
> 
> I hope you can help me solve this problem，thanks



> Hi, I also encountered the same problem. My input file is as follows. Errors will occur when using spaces and tabs as delimiters GIANT.txt SNP A1 A2 BETA P N rs10 A C 0.0333 0.708 80566 rs1000000 G A 0.6333 0.506 123865 rs10000010 C T 0.425 0.736 123827 rs10000012 C G 0.8083 0.042 123809 rs10000013 C A 0.1667 0.0689 123863 rs10000017 T C 0.2333 0.457 123262 rs1000002 C T 0.475 0.0322 123783 rs10000023 T G 0.5917 0.939 123756 rs10000029 T C 0.975 0.24 103623 rs1000003 G A 0.125 0.293 123743
> 
> w_hm3.snplist SNP A1 A2 rs10 A C rs1000000 G A rs10000010 C T rs10000012 C G rs10000013 C A rs10000017 T C rs1000002 C T rs10000023 T G rs10000029 T C rs1000003 G A
> 
> Run Command munge_sumstats.py --sumstats GIANT.txt --merge-alleles w_hm3.snplist --snp SNP --out test
> 
> I hope you can help me solve this problem，thanks
Use the \t as delimiters. I hope this helps you.

**Comment by CandyLucky** [comment]
Thank you. I tried using \t and space as delimiters, but the same error message appeared. My file is as follows:
SNP A1 A2 BETA P N
SNP A1 A2

**Comment by 731104** [comment]
> So your delimiters are \t and space, is this correct? I only use  \t as delimiters.

**Comment by CandyLucky** [comment]
I tried using \t and space separately, and both methods gave an error.

**Comment by 731104** [comment]
Can u show me your code, I am a  little confused.

**Comment by CandyLucky** [comment]
python munge_sumstats.py --sumstats GIANT.table.txt  --merge-alleles w_hm3.table.snplist --out GIANT --a1-inc

**Comment by 731104** [comment]
Try this command

./munge_sumstats.py \
--sumstats GIANT.table.txt \
--N N \
--snp SNP \
--a1 A1 \
--a2 A2 \
--out GIANT \
--signed-sumstats BETA,0 \
--merge-alleles w_hm3.snplist.txt

**Comment by CandyLucky** [comment]
Thank you very much for your reply, but I still get the same error.

**Comment by 731104** [comment]
My reply did not show ” \“. That was weired. The code must be end with "space \“.

**Comment by CandyLucky** [comment]
Sorry, I don't fully understand what you mean. Is this the command?
/munge_sumstats.py --sumstats GIANT.table.txt --snp SNP --a1 A1 --a2 A2 --N N --out GIANT --signed-sumstats BETA,0 --merge-alleles w_hm3.table.snplist \

**Comment by 731104** [comment]
/munge_sumstats.py \--sumstats GIANT.table.txt \--snp SNP \--a1 A1 \--a2 A2 \--N N \--out GIANT \--signed-sumstats BETA,0 \--merge-alleles w_hm3.table.snplist

**Comment by 731104** [comment]
![Uploading 微信图片_20241120150511.png…]()
Can u see this, I mean, space \ in every command that input.

**Comment by RXMa-Bio-software** [comment]
sorry ,I don't can  see image

**Comment by CandyLucky** [comment]
Thank you very much for your reply, but I don't can see image
