### ISSUE TITLE
Error calculating heritability

### ISSUE THREAD

**Issue by DelnazRoshandel** [bulik/ldsc#389]
I am trying to calculate heritability and getting this error:

Reading regression weight LD Score from baselineLD_v2.3/baselineLD.[1-22] ... (ldscore_fromlist)
Traceback (most recent call last):
  File "/hpf/tools/centos7/ldsc/1.0.1/ldsc.py", line 644, in <module>
    sumstats.estimate_h2(args, log)
  File "/hpf/tools/centos7/ldsc/1.0.1/ldscore/sumstats.py", line 326, in estimate_h2
    args, log, args.h2)
  File "/hpf/tools/centos7/ldsc/1.0.1/ldscore/sumstats.py", line 247, in _read_ld_sumstats
    w_ld = _read_w_ld(args, log)
  File "/hpf/tools/centos7/ldsc/1.0.1/ldscore/sumstats.py", line 136, in _read_w_ld
    raise ValueError('--w-ld may only have one LD Score column.')
ValueError: --w-ld may only have one LD Score column.

I am wondering what causing the problem.

**Comment by aksarkar** [comment]
The files `baselineLD_v2.3/*` are not appropriate to use as regression weights in `--w_ld`.

You need to use the files in `1000G_Phase3_weights_hm3_no_MHC.tgz` (https://zenodo.org/record/7768714) for example.

**Comment by ruimin-1212** [comment]
> The files `baselineLD_v2.3/*` are not appropriate to use as regression weights in `--w_ld`.
> 
> You need to use the files in `1000G_Phase3_weights_hm3_no_MHC.tgz` (https://zenodo.org/record/7768714) for example.

I meet the same question.My code is
for i in {1..22}
do 
python ./ldsc.py --h2 hearta.sumstats.gz  --out aCM --ref-ld-chr aCM/Add_all.chr${i} --w-ld-chr 1000G_Phase3_weights_hm3_no_MHC/weights.hm3_noMHC.${i} 
Done
Interestingly, chr1 and chr2 can be executed with no error. The index error begins from the third chromosome
