### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by yijiesung** [bulik/ldsc#400]
when i run:
`munge_sumstats.py \
    --sumstats BBJ_HDLC.txt.gz \
    --merge-alleles $snplist \
    --a1 ALT \
    --a2 REF \
    --chunksize 500000 \
    --out BBJ_HDLC`
it returns:
`Traceback (most recent call last):
  File "munge_sumstats.py", line 548, in munge_sumstats
    log.log(header)
  File "~/tools/ldsc/ldsc.py", line 84, in log
    print(msg, file=self.log_fh)
TypeError: a bytes-like object is required, not 'str'
`
env info:
- python=3.6
- bitarray=0.8
- nose=1.3
- pybedtools=0.7
- pip
- pip:
  - scipy==0.18
  - pandas==0.20
  - numpy==1.16

Has anyone encountered such a problem? how should I solve this？

**Comment by aksarkar** [comment]
The version of ldsc here does not support Python 3. You will need to run it through `2to3` at a minimum to get it to work.
