### ISSUE TITLE
，

### ISSUE THREAD

**Issue by yankvss** [bulik/ldsc#404]
When I run munge_sumstats.py, the error is
What am I supposed to do

ERROR converting summary statistics:
What am I supposed to do
Traceback (most recent call last):
  File "munge_sumstats.py", line 662, in munge_sumstats
    delim_whitespace=True, na_values='.')
  File "/home/yan/anaconda3/envs/ldsc/lib/python2.7/site-packages/pandas/io/parsers.py", line 702, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/yan/anaconda3/envs/ldsc/lib/python2.7/site-packages/pandas/io/parsers.py", line 435, in _read
    data = parser.read(nrows)
  File "/home/yan/anaconda3/envs/ldsc/lib/python2.7/site-packages/pandas/io/parsers.py", line 1139, in read
    ret = self._engine.read(nrows)
  File "/home/yan/anaconda3/envs/ldsc/lib/python2.7/site-packages/pandas/io/parsers.py", line 1995, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 899, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 914, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 968, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 955, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 2172, in pandas._libs.parsers.raise_parser_error
ParserError: Error tokenizing data. C error: Expected 1 fields in line 3, saw 2

Conversion finished at Thu Sep 21 21:12:11 2023
Total time elapsed: 0.04s
Traceback (most recent call last):
  File "munge_sumstats.py", line 745, in <module>
    munge_sumstats(parser.parse_args(), p=True)
  File "munge_sumstats.py", line 662, in munge_sumstats
    delim_whitespace=True, na_values='.')
  File "/home/yan/anaconda3/envs/ldsc/lib/python2.7/site-packages/pandas/io/parsers.py", line 702, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/yan/anaconda3/envs/ldsc/lib/python2.7/site-packages/pandas/io/parsers.py", line 435, in _read
    data = parser.read(nrows)
  File "/home/yan/anaconda3/envs/ldsc/lib/python2.7/site-packages/pandas/io/parsers.py", line 1139, in read
    ret = self._engine.read(nrows)
  File "/home/yan/anaconda3/envs/ldsc/lib/python2.7/site-packages/pandas/io/parsers.py", line 1995, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 899, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 914, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 968, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 955, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 2172, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 3, saw 2

**Comment by potatoj210** [comment]
Hi,
I am facing exact error right now. Could you please tell me how you solved it?

Thank you ahead of time

Best wishes,
Qianshu
