### ISSUE TITLE
make_annot.py does not run

### ISSUE THREAD

**Issue by VitorAguiar** [bulik/ldsc#440]
Hello, 

I just got a fresh copy of ldsc and have followed the steps to create a conda environment. 

I am able to execute 

```
python2.7 ./ldsc.py -h
python2.7 ./munge_sumstats.py -h
```

However `make_annot.py -h` hangs forever. When I cancel it with Ctrl-C, I get this message:

```
^CTraceback (most recent call last):
  File "./make_annot.py", line 6, in <module>
    from pybedtools import BedTool
  File "/home/miniconda3/envs/ldsc/lib/python2.7/site-packages/pybedtools/__init__.py", line 17, in <module>
    from .bedtool import BedTool
  File "/home/miniconda3/envs/ldsc/lib/python2.7/site-packages/pybedtools/bedtool.py", line 380, in <module>
    class BedTool(object):
  File "/home/miniconda3/envs/ldsc/lib/python2.7/site-packages/pybedtools/bedtool.py", line 2124, in BedTool
    @_wraps(prog='pairToPair', implicit='a', other='b')
  File "/home/miniconda3/envs/ldsc/lib/python2.7/site-packages/pybedtools/bedtool.py", line 162, in _wraps
    help_str = p.communicate()[1].decode()
  File "/home/miniconda3/envs/ldsc/lib/python2.7/subprocess.py", line 483, in communicate
    return self._communicate(input)
  File "/home/miniconda3/envs/ldsc/lib/python2.7/subprocess.py", line 1124, in _communicate
    stdout, stderr = self._communicate_with_poll(input)
  File "/home/miniconda3/envs/ldsc/lib/python2.7/subprocess.py", line 1178, in _communicate_with_poll
    ready = poller.poll()
KeyboardInterrupt
```

In our cluster, we have a python.pybedtools available, and running the code below works.

```
python.pybedtools ./make_annot.py -h
```

However, and I run the actual command with input files, it fails with the error below. 

```
$ python.pybedtools make_annot.py --bed-file $BED --bimfile $BIM --annot-file $OUT

making annot file
Traceback (most recent call last):
  File "make_annot.py", line 56, in <module>
    make_annot_files(args, bed_for_annot)
  File "make_annot.py", line 23, in make_annot_files
    iter_bim = [['chr'+str(x1), x2 - 1, x2] for (x1, x2) in np.array(df_bim[['CHR', 'BP']])]
TypeError: unsupported operand type(s) for -: 'str' and 'int'
```

I would appreciate any help.
Thank you!

**Comment by aksarkar** [comment]
@VitorAguiar The last error message suggests that the BP field of the BIM file is being parsed as `str` not `int`.

Are there missing positions in your BIM file? These are usually given as "." and would likely need to be removed.

**Comment by VitorAguiar** [comment]
Thank you @aksarkar, the BIM was not properly formatted.
