### ISSUE TITLE
Validate expected dtypes in munge_sumstats

### ISSUE THREAD

**Issue by ofrei** [bulik/ldsc#58]
Getting an error when reading summary statistics from plain text file using ``mungle_sumstats.py``
(note high number of SNPs with P outside `(0, 1]`, and `DtypeWarning: Columns (4,6) have mixed types`).
```
> python .\munge_sumstats.py --sumstats myfile.txt --out DMG --merge-alleles w_hm3.snplist --N 1800
*********************************************************************
* LD Score Regression (LDSC)
* Version 1.0.0
* (C) 2014-2015 Brendan Bulik-Sullivan and Hilary Finucane
* Broad Institute of MIT and Harvard / MIT Department of Mathematics
* GNU General Public License v3
*********************************************************************
Call:
./munge_sumstats.py \
--out DMG \
--merge-alleles w_hm3.snplist \
--N 1800.0 \
--sumstats myfile.txt

Interpreting column names as follows:
INFO:   INFO score (imputation quality; higher --> better imputation)
MarkerName:     Variant ID (e.g., rs number)
A1:     Allele 1, interpreted as ref allele for signed sumstat.
P:      p-Value
FRQ:    Allele frequency
A2:     Allele 2, interpreted as non-ref allele for signed sumstat.
OR:     Odds ratio (1 --> no effect; above 1 --> A1 is risk increasing)

Reading list of SNPs for allele merge from w_hm3.snplist
Read 1217311 SNPs for allele merge.
Reading sumstats from myfile.txt into memory 5000000 SNPs at a time.
.\munge_sumstats.py:707: DtypeWarning: Columns (4,6) have mixed types. Specify dtype option on import or set low_memory=False.
  munge_sumstats(parser.parse_args(), p=True)
.WARNING: 738871 SNPs had P outside of (0,1]. The P column may be mislabeled.
.WARNING: 322561 SNPs had P outside of (0,1]. The P column may be mislabeled.
 done
Read 6979536 SNPs from --sumstats file.
Removed 5829331 SNPs not in --merge-alleles.
Removed 0 SNPs with missing values.
Removed 286025 SNPs with INFO <= 0.9.
Removed 1849 SNPs with MAF <= 0.01.
Removed 795182 SNPs with out-of-bounds p-values.
Removed 0 variants that were not SNPs or were strand-ambiguous.
67149 SNPs remain.
Removed 0 SNPs with duplicated rs numbers (67149 SNPs remain).
Using N = 1800.0

ERROR converting summary statistics:

Traceback (most recent call last):
  File ".\munge_sumstats.py", line 658, in munge_sumstats
    dat.P = p_to_z(dat.P, dat.N)
  File ".\munge_sumstats.py", line 366, in p_to_z
    return np.sqrt(chi2.isf(P, 1))
  File "C:\Anaconda2\lib\site-packages\scipy\stats\_distn_infrastructure.py", line 1891, in isf
    place(output, cond, self._isf(*goodargs) * scale + loc)
  File "C:\Anaconda2\lib\site-packages\scipy\stats\_continuous_distns.py", line 843, in _isf
    return special.chdtri(df, p)
TypeError: ufunc 'chdtri' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''


Conversion finished at Wed Sep 21 14:55:43 2016
Total time elapsed: 25.01s
Traceback (most recent call last):
  File ".\munge_sumstats.py", line 707, in <module>
    munge_sumstats(parser.parse_args(), p=True)
  File ".\munge_sumstats.py", line 658, in munge_sumstats
    dat.P = p_to_z(dat.P, dat.N)
  File ".\munge_sumstats.py", line 366, in p_to_z
    return np.sqrt(chi2.isf(P, 1))
  File "C:\Anaconda2\lib\site-packages\scipy\stats\_distn_infrastructure.py", line 1891, in isf
    place(output, cond, self._isf(*goodargs) * scale + loc)
  File "C:\Anaconda2\lib\site-packages\scipy\stats\_continuous_distns.py", line 843, in _isf
    return special.chdtri(df, p)
TypeError: ufunc 'chdtri' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```
There is indeed a small problem with my input file: it is  tab-delimited (strictly one tab between columns) and encodes ``NaN`` values as empty string. This combination does not work with ``pd.read_csv(delim_whitespace=True)``, because it treats ``\t\t`` as a single space. Then the content of the columns is mixed, and pandas fails to detect correct column type. The p-value column end up having ``dtype(object)``, and this explains p-values outside `(0, 1]`. But this is non-intuitive and it would be great to get back an explicit error message. 

In my fork I fixed this by adding a simple check in ``parse_dat`` method:
```
numeric_cols = ['P', 'N', 'N_CAS', 'N_CON', 'Z', 'OR', 'BETA',
                'LOG_ODDS', 'INFO', 'FRQ', 'SIGNED_SUMSTAT', 'NSTUDY']
wrong_types = [c for c in dat.columns
               if c in numeric_cols and not np.issubdtype(dat[c].dtype, np.number)]
if len(wrong_types) > 0:
    raise ValueError('Columns {} are expected to be numeric'.format(wrong_types))
```
Should I open a pull request for this?

**Comment by rkwalters** [comment]
Hi Oleksandr,
This is a good catch, and I agree that at minimum we should produce a more informative error message here. 

Definitely go ahead an open the pull request. It will probably need some discussion of whether this is the best solution (vs. e.g. whether we need to add an option to pass delimiter information) and some testing of different use cases, but we can handle that in the pull request thread.

Thanks,
Raymond
