### ISSUE TITLE
Errors in tests with nosetests

### ISSUE THREAD

**Issue by jocen** [bulik/ldsc#64]
This bug may be related to error #36, which was closed a year ago.

I am running into failures on different Linux/Python installations, none can pass any of the two nosetest tests, with different errors for the `slow` and `not slow` tests.

LDSC version from commit f7c3316d4cc4012afd26743f56052389dd512d9c (9/11/2016)

Systems tested (all 64 bit):

 System          | Inst.  | Python |  NumPy |  SciPy | Pandas
-----------------|--------|--------|--------|--------|--------
 Ubuntu 14.04LTS | OS repos  |  2.7.6 | 1.11.2 | 0.13.3 | 0.19.1
 Debian 8        | OS repos  |  2.7.9 |  1.8.2 | 0.14.0 | 0.17.1
 Ubuntu 14.04LTS | Anacondas 4.20 | 2.7.12 | 1.11.2 | 0.18.1 | 0.19.1

```
jo@jo-ThinkPad:/tmp/ldsc$ nosetests-2.7 -A 'slow'
.........................F....
======================================================================
FAIL: test_sumstats.Test_RG_Statistical.test_hsq_int_se
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/ldsc/test/test_sumstats.py", line 274, in test_hsq_int_se
    map(t('intercept'), map(t('hsq2'), self.rg))), atol=0.1)
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/utils.py", line 1392, in assert_allclose
    verbose=verbose, header=header)
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/utils.py", line 739, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0.1

(mismatch 100.0%)
 x: array(0.5372853385973988)
 y: array(0.6539727418594191)

----------------------------------------------------------------------
Ran 30 tests in 48.827s

FAILED (failures=1)
```

For the `not slow` tests:

```
jo@jo-ThinkPad:/tmp/ldsc$ nosetests -A 'not slow'
..........................................................................................................E............E..E.E............
======================================================================
ERROR: test_summary (test_regressions.Test_Hsq_2D)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/ldsc/test/test_regressions.py", line 200, in test_summary
    self.chisq, self.ld, self.w_ld, self.N, self.M, n_blocks=3)
  File "/tmp/ldsc/ldscore/regressions.py", line 346, in __init__
    slow=slow, step1_ii=step1_ii, old_weights=old_weights)
  File "/tmp/ldsc/ldscore/regressions.py", line 213, in __init__
    x, yp, update_func, n_blocks, slow=slow, w=initial_w)
  File "/tmp/ldsc/ldscore/irwls.py", line 66, in __init__
    x, y, update_func, n_blocks, w, slow=slow, separators=separators)
  File "/tmp/ldsc/ldscore/irwls.py", line 127, in irwls
    x, y, n_blocks, separators=separators)
  File "/tmp/ldsc/ldscore/jackknife.py", line 309, in __init__
    self.est = self.block_values_to_est(xty, xtx)
  File "/tmp/ldsc/ldscore/jackknife.py", line 386, in block_values_to_est
    return np.linalg.solve(xtx, xty).reshape((1, p))
  File "/usr/local/lib/python2.7/dist-packages/numpy/linalg/linalg.py", line 384, in solve
    r = gufunc(a, b, signature=signature, extobj=extobj)
  File "/usr/local/lib/python2.7/dist-packages/numpy/linalg/linalg.py", line 90, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
LinAlgError: Singular matrix

======================================================================
ERROR: test_h2_ref_ld (test_sumstats.Test_Estimate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/ldsc/test/test_sumstats.py", line 389, in test_h2_ref_ld
    x = s.estimate_h2(args, log)
  File "/tmp/ldsc/ldscore/sumstats.py", line 265, in estimate_h2
    args, log, args.h2)
  File "/tmp/ldsc/ldscore/sumstats.py", line 247, in _read_ld_sumstats
    sumstats = _merge_and_log(ref_ld, sumstats, 'reference panel LD', log)
  File "/tmp/ldsc/ldscore/sumstats.py", line 230, in _merge_and_log
    sumstats = smart_merge(ld, sumstats)
  File "/tmp/ldsc/ldscore/sumstats.py", line 69, in smart_merge
    if len(x) == len(y) and (x.SNP == y.SNP).all():
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/ops.py", line 812, in wrapper
    raise ValueError(msg)
ValueError: Can only compare identically-labeled Series objects
-------------------- >> begin captured stdout << ---------------------
Reading summary statistics from /tmp/ldsc/test/simulate_test/sumstats/555 ...
Read summary statistics for 1000 SNPs.
Reading reference panel LD Score from /tmp/ldsc/test/simulate_test/ldscore/twold_onefile[1-22] ...
Read reference panel LD Scores for 1000 SNPs.
Removing partitioned LD Scores with zero variance.
Reading regression weight LD Score from /tmp/ldsc/test/simulate_test/ldscore/w ...
Read regression weight LD Scores for 1000 SNPs.

--------------------- >> end captured stdout << ----------------------

======================================================================
ERROR: test_rg_ref_ld (test_sumstats.Test_Estimate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/ldsc/test/test_sumstats.py", line 434, in test_rg_ref_ld
    x = s.estimate_rg(args, log)[0]
  File "/tmp/ldsc/ldscore/sumstats.py", line 336, in estimate_rg
    alleles=True, dropna=True)
  File "/tmp/ldsc/ldscore/sumstats.py", line 247, in _read_ld_sumstats
    sumstats = _merge_and_log(ref_ld, sumstats, 'reference panel LD', log)
  File "/tmp/ldsc/ldscore/sumstats.py", line 230, in _merge_and_log
    sumstats = smart_merge(ld, sumstats)
  File "/tmp/ldsc/ldscore/sumstats.py", line 69, in smart_merge
    if len(x) == len(y) and (x.SNP == y.SNP).all():
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/ops.py", line 812, in wrapper
    raise ValueError(msg)
ValueError: Can only compare identically-labeled Series objects
-------------------- >> begin captured stdout << ---------------------
Reading summary statistics from /tmp/ldsc/test/simulate_test/sumstats/1 ...
Read summary statistics for 1000 SNPs.
Reading reference panel LD Score from /tmp/ldsc/test/simulate_test/ldscore/twold_onefile[1-22] ...
Read reference panel LD Scores for 1000 SNPs.
Removing partitioned LD Scores with zero variance.
Reading regression weight LD Score from /tmp/ldsc/test/simulate_test/ldscore/w ...
Read regression weight LD Scores for 1000 SNPs.

--------------------- >> end captured stdout << ----------------------

======================================================================
ERROR: test_twostep_rg (test_sumstats.Test_Estimate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/ldsc/test/test_sumstats.py", line 483, in test_twostep_rg
    x = s.estimate_rg(args, log)[0]
  File "/tmp/ldsc/ldscore/sumstats.py", line 336, in estimate_rg
    alleles=True, dropna=True)
  File "/tmp/ldsc/ldscore/sumstats.py", line 247, in _read_ld_sumstats
    sumstats = _merge_and_log(ref_ld, sumstats, 'reference panel LD', log)
  File "/tmp/ldsc/ldscore/sumstats.py", line 230, in _merge_and_log
    sumstats = smart_merge(ld, sumstats)
  File "/tmp/ldsc/ldscore/sumstats.py", line 69, in smart_merge
    if len(x) == len(y) and (x.SNP == y.SNP).all():
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/ops.py", line 812, in wrapper
    raise ValueError(msg)
ValueError: Can only compare identically-labeled Series objects
-------------------- >> begin captured stdout << ---------------------
Reading summary statistics from /tmp/ldsc/test/simulate_test/sumstats/1 ...
Read summary statistics for 1000 SNPs.
Reading reference panel LD Score from /tmp/ldsc/test/simulate_test/ldscore/oneld_onefile[1-22] ...
Read reference panel LD Scores for 1000 SNPs.
Removing partitioned LD Scores with zero variance.
Reading regression weight LD Score from /tmp/ldsc/test/simulate_test/ldscore/w ...
Read regression weight LD Scores for 1000 SNPs.

--------------------- >> end captured stdout << ----------------------

----------------------------------------------------------------------
Ran 137 tests in 2.202s

FAILED (errors=4)
```

**Comment by rkwalters** [comment]
Hi,
Thanks for checking on this. We’re aware of the ‘slow’ test failure, and have looked into it some, but haven’t figured out the cause yet. The ‘not slow’ failures are new to me, but from an initial look appear to all be issues with how the tests are written rather than the underlying code being tested. 

Suspect you are correct that this is related to #36. The corresponding commit (a4a29a2) appears to still fail nosetests on my setup, though the ‘not slow’ errors are different (suspect at least some of them are related to pandas versioning).

Will try to get these all addressed.
Cheers,
Raymond

**Comment by 0xaf1f** [comment]
With the current version (1.0.0-92-gcf1707e) installed on CentOS 6, I'm seeing only one failure, and it's in the slow set:

```
$ NOSE_EVAL_ATTR="not slow" ldsc-python-wrapper -m nose
.........................................................................................................................................
----------------------------------------------------------------------
Ran 137 tests in 3.793s

OK
$ NOSE_EVAL_ATTR="slow" python -m nose
.........................F....
======================================================================
FAIL: test_sumstats.Test_RG_Statistical.test_hsq_int_se
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/Anaconda/envs/py2.7/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/spin1/scratch/teacher/ldsc/test/test_sumstats.py", line 274, in test_hsq_int_se
    map(t('intercept'), map(t('hsq2'), self.rg))), atol=0.1)
  File "/usr/local/Anaconda/envs/py2.7/lib/python2.7/site-packages/numpy/testing/utils.py", line 1392, in assert_allclose
    verbose=verbose, header=header)
  File "/usr/local/Anaconda/envs/py2.7/lib/python2.7/site-packages/numpy/testing/utils.py", line 739, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0.1

(mismatch 100.0%)
 x: array(0.5372853385973987)
 y: array(0.6539727418594191)

----------------------------------------------------------------------
Ran 30 tests in 51.130s

FAILED (failures=1)
```

My dependency versions:

```
$ python --version
Python 2.7.13 :: Continuum Analytics, Inc.

$ python -c "import numpy; print numpy.version.version"
1.11.2

$ python -c "import scipy; print scipy.version.version"
0.18.1

$ python -c "import pandas; print pandas.__version__"
0.19.1
```

**Comment by rkwalters** [comment]
Hi Afif,
Yeah, the failing test was fixed by #113. The source of the failing test was that the number of simulated dataset replicates used for testing had been reduced at some point, introducing noise outside of the tolerance ranges. Increasing the number of replicates used in the tests resolved the error. 

Sorry for not circling back here to confirm the issue had been addressed.

Cheers,
Raymond
