### ISSUE TITLE
Error while partitioning heritability with the baseline model

### ISSUE THREAD

**Issue by hhautakangas** [bulik/ldsc#77]
Hi,

does anyone know, what could be wrong when I receive this error message:

Reading annot matrix from ----/Filtered_baseline.[1-22] ...
Traceback (most recent call last):
  File ".../ldsc/ldsc.py", line 644, in <module>
    sumstats.estimate_h2(args, log)
  File ".../ldsc/ldscore/sumstats.py", line 372, in estimate_h2
    df_results = hsqhat._overlap_output(ref_ld_cnames, overlap_matrix, M_annot, M_tot, args.print_coefficients)
  File ".../ldsc/ldscore/regressions.py", line 398, in _overlap_output
    overlap_matrix_prop[i, :] = overlap_matrix[i, :] / M_annot
ValueError: could not broadcast input array from shape (53) into shape (1)

Many thanks,
Heidi

**Comment by rkwalters** [comment]
Hi Heidi,
The error looks like some sort of mismatch in the expected number of annotations. Is it possible there’s something unusual about your input files for partitioning? (Empty annotations, extra/unused columns, mismatched M values, etc)

Would probably need to know more about your full command line call and the structure of “Filtered_baseline” to debug further.

Cheers,
Raymond
