### ISSUE TITLE
Question about partition heritability stratified by allele freqency

### ISSUE THREAD

**Issue by sandyren** [bulik/ldsc#84]
Recently, I have been trying to use LD regression to estimate heritability for each allele frequency range in my data. I read the tutorial from github and understand that I need to calculate partition ld score first according to the customized annotation file. However, when I tried to execute the following commands in Ubuntu system: Call:
./ldsc.py \
--ld-wind-cm 1.0 \
--out gendep_annot1 \
--bfile tmp \
--yes-really  \
--annot gendep_annot1.annot \
--l2  

Following error showed up :

Traceback (most recent call last):
  File "./ldsc.py", line 604, in <module>
    ldscore(args, log)
  File "./ldsc.py", line 306, in ldscore
    lN = geno_array.ldScoreVarBlocks(block_left, args.chunk_size, annot=annot_matrix)
  File "/media/sandy/DATA/ldsc/ldscore/ldscore.py", line 125, in ldScoreVarBlocks
    return self.__corSumVarBlocks__(block_left, c, func, snp_getter, annot)
  File "/media/sandy/DATA/ldsc/ldscore/ldscore.py", line 215, in __corSumVarBlocks__
    A = A[:, b0-b:b0]
TypeError: slice indices must be integers or None or have an __index__ method

Analysis finished at Thu Jun 15 16:55:27 2017
Total time elapsed: 35.52s
Traceback (most recent call last):
  File "./ldsc.py", line 604, in <module>
    ldscore(args, log)
  File "./ldsc.py", line 306, in ldscore
    lN = geno_array.ldScoreVarBlocks(block_left, args.chunk_size, annot=annot_matrix)
  File "/media/sandy/DATA/ldsc/ldscore/ldscore.py", line 125, in ldScoreVarBlocks
    return self.__corSumVarBlocks__(block_left, c, func, snp_getter, annot)
  File "/media/sandy/DATA/ldsc/ldscore/ldscore.py", line 215, in __corSumVarBlocks__
    A = A[:, b0-b:b0]
TypeError: slice indices must be integers or None or have an __index__ method

I then tried the simplest way to calculate ld score: Call: 

./ldsc.py \
--ld-wind-cm 1.0 \
--out tmp \
--bfile tmp \
--l2  

the same error showed up again. 

Many apologies that I am quite new in using Python, it would be much appreciated if you could help me debug the problem.

**Comment by rkwalters** [comment]
Hello,
Can you check whether you’re using the latest vesion of ldsc? (e.g. do a fresh pull from the github.) I haven’t been able to reproduce your error yet, and I’m guessing this commit <https://github.com/bulik/ldsc/commit/c42e055c68e1be9a9c4bb27c7e5b544826b44f43> may have fixed the integer index issue. If that doesn’t solve it, than knowing what “tmp” bfile you’re inputting would be helpful for debugging.

I’m also CCing Varun, since he reported a similar issue to the user group in February. It looks like we hadn’t found a solution at that time, so I’m guessing that either this thread will be relevant to him or he may have a solution.

Cheers,
Raymond
