### ISSUE TITLE
Errors running

### ISSUE THREAD

**Issue by skanoni** [bulik/ldsc#93]
Hi,

I am testing LDSC with the example files and I am getting the following errors. Could you please help me troubleshoot?

*********************************************************************
* LD Score Regression (LDSC)
* Version 1.0.0
* (C) 2014-2015 Brendan Bulik-Sullivan and Hilary Finucane
* Broad Institute of MIT and Harvard / MIT Department of Mathematics
* GNU General Public License v3
*********************************************************************
Call: 
./munge_sumstats.py \
--out scz \
--merge-alleles w_hm3.snplist \
--N 17115.0 \
--sumstats pgc.cross.SCZ17.2013-05.txt 

Interpreting column names as follows:
info:	INFO score (imputation quality; higher --> better imputation)
snpid:	Variant ID (e.g., rs number)
a1:	Allele 1, interpreted as ref allele for signed sumstat.
pval:	p-Value
a2:	Allele 2, interpreted as non-ref allele for signed sumstat.
or:	Odds ratio (1 --> no effect; above 1 --> A1 is risk increasing)

Reading list of SNPs for allele merge from w_hm3.snplist
Read 1217311 SNPs for allele merge.
Reading sumstats from pgc.cross.SCZ17.2013-05.txt into memory 5000000 SNPs at a time.
Read 1237958 SNPs from --sumstats file.
Removed 137131 SNPs not in --merge-alleles.
Removed 0 SNPs with missing values.
Removed 256286 SNPs with INFO <= 0.9.
Removed 0 SNPs with MAF <= 0.01.
Removed 0 SNPs with out-of-bounds p-values.
Removed 2 variants that were not SNPs or were strand-ambiguous.
844539 SNPs remain.
Removed 0 SNPs with duplicated rs numbers (844539 SNPs remain).
Using N = 17115.0
Median value of or was 1.0, which seems sensible.
Removed 39 SNPs whose alleles did not match --merge-alleles (844500 SNPs remain).

ERROR converting summary statistics:

Traceback (most recent call last):
  File "./munge_sumstats.py", line 701, in munge_sumstats
    dat = allele_merge(dat, merge_alleles, log)
  File "./munge_sumstats.py", line 439, in allele_merge
    dat.loc[~jj, [i for i in dat.columns if i != 'SNP']] = float('nan')
  File "/python2/lib/python2.7/site-packages/pandas/core/indexing.py", line 193, in __setitem__
    indexer = self._get_setitem_indexer(key)
  File "/python2/lib/python2.7/site-packages/pandas/core/indexing.py", line 171, in _get_setitem_indexer
    return self._convert_tuple(key, is_setter=True)
  File "/python2/lib/python2.7/site-packages/pandas/core/indexing.py", line 242, in _convert_tuple
    idx = self._convert_to_indexer(k, axis=i, is_setter=is_setter)
  File "/python2/lib/python2.7/site-packages/pandas/core/indexing.py", line 1269, in _convert_to_indexer
    .format(mask=objarr[mask]))
KeyError: '[-1 -1 -2 ..., -1 -1 -1] not in index'

Conversion finished at Fri Nov  3 11:52:40 2017
Total time elapsed: 40.27s

**Comment by anthony-aylward** [comment]
For me this was caused by pandas version 0.21.0, and I solved the problem by downgrading to pandas 0.20.1

```
pip uninstall pandas
pip install pandas==0.20.1
```

**Comment by ParsaAkbari** [comment]
The error seems to persist with pandas 0.22
